### ISSUE TITLE
what is null base URL for an embedded json-ld?

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-syntax#103]
This issue came up in the Publishing Working Group, see https://github.com/w3c/wpub/issues/374. The question is what exactly the JSON-LD processor's behavior should be if, for some reasons the `baseURI` value for the `<script>` element is null. An example for such a situation is in https://github.com/w3c/wpub/issues/374#issuecomment-444537196, brought up by @danielweck.

**Comment by danielweck** [comment]
In the JSON-LD processing model, what happens when a relative "path" cannot be resolved to an absolute URL due to unsuitable baseURI (e.g. null, or `data:` URL)?

1) complete failure (i.e. abort the processing algorithm)
or:
2) skip the unresolved URL (i.e. ignore the referenced resource), and continue processing.

https://github.com/w3c/wpub/issues/374#issuecomment-444798500

**Comment by ajs6f** [comment]
I believe that a `null` base URI [is explicitly allowed](https://w3c.github.io/json-ld-api/#dom-jsonlderrorcode-invalid-base-iri), at least in our editor's draft.

**Comment by ajs6f** [comment]
My reading of what I believe to be the [relevant piece of RFC](https://tools.ietf.org/html/rfc3986#section-5.2) gives us a `null` base URI with all components undefined except an empty path.

**Comment by gkellogg** [comment]
This is quite similar to what would happen to another RDF serialization, such as RDFa or Turtle, if there were no base IRI established. In those cases, processors will not generate absolute IRIs, which is invalid, but potentially useful. (My own processors allow this, unless set to a `validate` mode). Typically, as these are web specs, documents are considered to have a location which is the fallback for the base IRI. But, in some cases they don't.

The [IRI Expansion Algorithm](https://w3c.github.io/json-ld-api/#iri-expansion) has two cases: if we are doing _document relative_ expansion, or not. As @ajs6f points out, in the _document relative_ case, RFC3986 applies, but the result will end up being a still relative IRI (provided that the input is not already an absolute IRI). The fall-through case is the same if there is  no _vocabulary mapping_, and the relative IRI is returned.

Note that the [Deserialize JSON-LD to RDF Algorithm](Deserialize JSON-LD to RDF Algorithm) will not emit invalid triples, which would include any that have relative IRIs, as they are not considered valid RDF. However, implementations may have leeway in what they actually do if not in strict validation more. Otherwise, we're restricted by the RDF data model, which requires that IRIs be absolute (see [RDF 1.1 Concepts](https://www.w3.org/TR/rdf11-concepts/#resources-and-statements):

>An RDF triple consists of three components:
> * the subject, which is an IRI or a blank node
> * the predicate, which is an IRI
> * the object, which is an IRI, a literal or a blank node

> An IRI (Internationalized Resource Identifier) within an RDF graph is a Unicode string [UNICODE] that conforms to the syntax defined in RFC 3987 [RFC3987].

> IRIs in the RDF abstract syntax must be absolute, and may contain a fragment identifier.

I'm not clear that we should say anything more about it in the spec.

@ajs6f assertion that it is explicitly allowed, is not generally true, as the cited error message is specifically for values of `@base`, and setting `@base` to `null` unassigns the value, reverting to the document location.

**Comment by iherman** [comment]
@gkellogg what is not clear to me (sorry, I am not familiar with all the details of the API spec) is whether an implementation is supposed to raise the error and exactly under what circumstances.

The issue came up in the WPUB work (and raised by @danielweck) on what a processor handling a Web Publication Manifest should do if an embedded manifest does not have a valid base value. My approach is that this behavior should be in line with what a JSON-LD processor would do in general...

**Comment by iherman** [comment]
I must admit I do not have a very clear idea either.

Looking at the alternatives by @danielweck (https://github.com/w3c/json-ld-syntax/issues/103#issuecomment-444800978), I guess both of them go one step further. I think aborting the full processing is probably to drastic; I am not sure what "skipping the unresolved URL" would mean for the different API-s. For an RDF generation I guess this would mean skipping all relevant triples, I am not sure about expansion and compaction.

I think that, at the minimum, a warning should be issued, fwiw. As you said, the generation of a relative URL in RDF indeed leads to a non-conformant (ie, possibly erroneous) RDF data.

Obviously, this is a very small corner case.

**Comment by dlongley** [comment]
It is useful behavior to be able to expand/compact without modifying URLs. My understanding is that when the base URL is explicitly set to `null`, a processor will skip URL processing and leave the values untouched during expansion/compaction. A base URL must be specified to convert to RDF (for conformance reasons). So I think what we've spec'd and what (I believe) the processors currently do is the right behavior.

**Comment by iherman** [comment]
@dlongley is there any warning/error raised by the processor?

**Comment by dlongley** [comment]
@iherman, no warning or error raised.

**Comment by iherman** [comment]
I believe there should be a warning at least. At the minimum when RDF is generated.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-08-09-json-ld#section4-2).

- `RESOLVED:  close #103 as wontfix because the JSON-LD document would be treated as if it were alone–and not embedded.`
<details><summary><i class="differentiate">View the transcript</i></summary>
What is null base URL for an embedded json-ld?<br/>
Ivan Herman: See Issue 103<br/>
Benjamin Young: the question is raised when JSON-LD is embedded in HTML or anything.<br/>
Ivan Herman: someone came up with this example involving data: URL and iframe,<br/>
… leading to a situation where the base URL is not clear.<br/>
Gregg Kellogg: the fact that it is in HTML does not change anything,<br/>
… the processor tries to determine the base URL based on the source document URL.<br/>
Proposed resolution: close #103 as wontfix because the JSON-LD document would be treated as if it were alone–and not embedded. (Benjamin Young)<br/>
Ivan Herman: the problem is the use of the data: URL. The question is not JSON-LD specific. It would be the same with HTML<br/>
Gregg Kellogg: this is a TAG issue<br/>
Ivan Herman: It is a HTML problem. Whatever HTML does, we do it.<br/>
Dave Longley: +1<br/>
Ruben Taelman: +1<br/>
Gregg Kellogg: +1<br/>
Benjamin Young: +1<br/>
Benjamin Young: and if HTML has no answer wrt to the base URL, then you are on your own.<br/>
Ivan Herman: +1<br/>
Pierre-Antoine Champin: +1<br/>
Tim Cole: +1<br/>
Resolution #4: close #103 as wontfix because the JSON-LD document would be treated as if it were alone–and not embedded.<br/>
</details>
