### ISSUE TITLE
Term definitions in context that support multiple values for @type?

### ISSUE THREAD

**Issue by tcole3** [w3c/json-ld-syntax#121]
As noted in another issue, https://github.com/w3c/json-ld-syntax/issues/20#issuecomment-459996322, and elsewhere, schema.org has several properties that can take a value which can be either a schema:Text or a schema:URL. For example, regarding the schema.org property _encodingFormat_ (which supersedes the _fileFormat_ property), schema.org suggests that values for this property be a: 
> "Media type typically expressed using a MIME format (see IANA site and MDN reference) e.g. _application/zip_ for a SoftwareApplication binary, _audio/mpeg_ for .mp3 etc.). ... Unregistered or niche encoding and file formats can be indicated instead via the most appropriate URL, e.g. defining Web page or a Wikipedia/Wikidata entry." 

Their 3 examples use string values for _encodingFormat_: image/png, audio/mpeg, text/html, text/javascript, and text/css, but as explicitly specified in the definition quoted above, a URL would also be an acceptable value for _encodingFormat_. 

Term definitions like this suggest a need for a new feature in json-ld that supports defining a term in a context so as to say that values for that term may be either a string or an @id (and similar combinations of primitive data types). 

Or possibly a way in json-ld context to support user defined types that are unions of primitive data types. 

Is this functionality already supported in some way? Or did this idea for a feature extension already come up in the Community Group and get rejected for some reason?

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-02-08-json-ld#section5-6).

- `RESOLVED:  Close #121 wontfix, as the solution that isn’t ambiguous is very very complicated {: #resolution11 .resolution}`
<details><summary><i class="differentiate">View the transcript</i></summary>
Term definitions in context that support multiple values for @type?<br/>
Rob Sanderson: ref: <a href="https://github.com/w3c/json-ld-syntax/issues/121">https://github.com/w3c/json-ld-syntax/issues/121</a><br/>
Rob Sanderson: this came out of the sealing discussion<br/>
… timc notes that schema.org has properties that take either text or resource<br/>
… should we be able to say that a property accepts either type A or type B but not type C<br/>
Gregg Kellogg: schema.org should have different properties for differently-typed values<br/>
Ivan Herman: not really practical for schema.org users<br/>
Rob Sanderson: you can rep this in the instance doc itself, inline<br/>
… I say close won’tfix because it is unambiguous but ugly<br/>
Gregg Kellogg: e.g. if you have a property ‘author’ it could have values of many different types<br/>
Rob Sanderson: validation is not JSON-LD’s job, just mapping<br/>
Ivan Herman: in the context of schemo.org, can they properly define that something is say, a resource or a text?/<br/>
Ivan Herman: is it a case of “if it can be parsed as a URI it should be treated as such”?<br/>
<b>general:</b> no, that’s too error-prone<br/>
Ivan Herman: they (schema.org) have a canonical order of expectation<br/>
Gregg Kellogg: and schema.org doesn’t really use linked data<br/>
Proposed resolution: Close #121 wontfix, as the solution that isn’t ambiguous is very very complicated (Rob Sanderson)<br/>
Ivan Herman: +1<br/>
Adam Soroka: +1<br/>
Rob Sanderson: +1<br/>
Gregg Kellogg: +<br/>
David Newbury: +1<br/>
David I. Lehn: +1<br/>
Benjamin Young: +0 (missed most of the debate)<br/>
Gregg Kellogg: also <a href="http://linter.structured-data.org,">http://linter.structured-data.org,</a> which does it’s best to figure it out.<br/>
Gregg Kellogg: +1<br/>
Jeff Mixter: +1<br/>
Resolution #11: Close #121 wontfix, as the solution that isn’t ambiguous is very very complicated {: #resolution11 .resolution}<br/>
Harold Solbrig: +1<br/>
</details>
