### ISSUE TITLE
Additional restriction to `@sealed` term clearing

### ISSUE THREAD

**Issue by dlongley** [w3c/json-ld-syntax#136]
We've completed a preliminary implementation of `@sealed` terms here:

https://github.com/digitalbazaar/jsonld.js/pull/289

Our implementation:

* Allows terms to be sealed using `"@sealed": true` in a term definition (or not sealed with `"@sealed": false`)
* Allows setting the default `"@sealed"` for all terms in an `@context` via `"@sealed": true` at the top level
* Does not affect existing term clearing rules when there are no `@sealed` terms
* **Allows clearing `@sealed` terms ONLY via a new property term definition with a scoped `@context` (note: and the new term does not need to be sealed)**

Note that the last item is a slight tweak (additional restriction) on what is in the spec. We believe this approach better matches the use cases and expectations of the target audience for JSON-only application developers. The high-level idea is that a `@sealed` term is assured to maintain its meaning unless cleared by a new term (with a scoped context) that creates a new branch in the JSON tree.

This approach:

* Provides sufficient assurance for the meaning of `@sealed` terms without a need for JSON-LD processing: a JSON-only dev can read a spec and write **safe** code that traverses JSON-LD data via `@sealed` terms ... without a need for JSON-LD processing, instead using only validation rules (e.g. json-schema)
* Allows extensions to the JSON tree to occur **safely** in an idiomatic way where `@sealed` terms can only be cleared under new branches in the JSON tree (matches common JSON developer intuitions/expectations)
* Very closely mirrors what @pchampin articulated so well a while back but has the added benefit of being simpler to implement: there is no need to track the `@context` from whence `@sealed` terms came

We'd like to see the spec updated to restrict clearing `@sealed` terms in the way articulated here and implemented in the above link. This approach seems to fully address the original need for the feature and has a simple implementation.

**Comment by gkellogg** [comment]
This looks like a middle ground between keeping track of sealed terms from different contexts and providing some impediment to simply wiping out sealed terms, which only takes effect when you've stepped into a different part of the JSON tree.

**Comment by iherman** [comment]
@dlongley, thanks. Just for my understanding, can you propose alternate versions of the examples 42-44? I am. e.g., not sure what you mean by "clearing".

Looking, e.g., in [Example 42](https://w3c.github.io/json-ld-syntax/#example-42-a-sealed-term-definition-can-not-be-overridden): does it mean that the second attempt to overwrite a term (namely as part of `"knows"`) _is_ acceptable in contrast to what the example say now? Or is this action permitted only for a term different from `"knows"`, i.e., a "new" term? 

My _feeling_ is that you mean the second option. But I am not sure…

**Comment by dlongley** [comment]
@iherman,

> I am. e.g., not sure what you mean by "clearing".

I mean that the active context is reset to the initial active context (a "clean slate" having no term definitions). If there are sealed terms in the active context when an attempt is made to reset it, this will fail unless the attempt that is made is via a term definition with a scoped context *and* that term is used as a property (as opposed to as a value for `@type`). More explanation to follow...

> does it mean that the second attempt to overwrite a term (namely as part of `"knows"`) _is_ acceptable in contrast to what the example say now? Or is this action permitted only for a term different from `"knows"`, i.e., a "new" term?

Actually, the current examples in the spec don't change at all; they are still correct with this new restriction. So, no, it is not acceptable. You *must* create a new term just like [Example 44](https://w3c.github.io/json-ld-syntax/#example-44-context-null-erases-sealed-term-definitions) does. However, this makes it more clear that *only* the way Example 44 does it is acceptable.

For instance, an example of something that *would not* be acceptable is this:

```js
{
  "@context": [
    {
      "@version": 1.1,
      "@sealed": true,
      "Organization": "http://schema.org/Organization",
      "name": "http://schema.org/name",
      "employee": "http://schema.org/employee"
    }
  ],
  "@type": "Organization",
  "name": "Digital Bazaar",
  "employee" : {
    "@context": [
       // because of "@context": null in an embedded context 
       // and not a scoped context, this `null` will fail and so
       // would the override attempt of name
      null,
      {
        "name": "this_attempt_to_override_name_will_fail"
      }
    ],
    "name": "Manu Sporny"
  }
}
```

Similarly, this would fail:

```js
{
  "@context": [
    {
      "@version": 1.1,
      "@sealed": true,
      "Organization": "http://schema.org/Organization",
      "name": "http://schema.org/name",
      "employee": "http://schema.org/employee",
      "SpecialOrganization": {
        "@id": "http://example.com/SpecialOrganization",
        // if the term for this definition is used as an "@type",
        // then this attempt to clear "@sealed" terms will fail
        "@context": [
          null,
          {
            "name": "this_attempt_to_override_name_will_fail",
            "employee": "this_attempt_to_override_name_will_fail"
          }
        ]
      }
    }
  ],
  // because of "@context": null in a scoped context for
  // a term used as an "@type" rather than as a property, its
  // term definition will fail
  "@type": ["Organization", "SpecialOrganization"],
  "name": "Digital Bazaar",
  "employee" : {
    "name": "Manu Sporny"
  }
}
```

**Comment by iherman** [comment]
@dlongley still trying to understand... If I did the following (sorry for the ugly code, but it is legal...)

```js
{
  "@context": [
    {
      "@version": 1.1,
      "@sealed": true,
      "Organization": "http://schema.org/Organization",
      "name": "http://schema.org/name",
      "employee": "http://schema.org/employee",
      "SpecialOrganization": {
        "@id": "http://example.com/SpecialOrganization",
        // if the term for this definition is used as an "@type",
        // then this attempt to clear "@sealed" terms will fail
        "@context": [
          null,
          {
            "name": "this_attempt_to_override_name_will_fail",
            "employee": "this_attempt_to_override_name_will_fail"
          }
        ]
      }
    }
  ],
  // because of "@context": null in a scoped context for
  // a term used as an "@type" rather than as a property, its
  // term definition will fail
  "@type": ["Organization", "SpecialOrganization"],
  "name": "Digital Bazaar",
  "employee" : {
    "name": "Manu Sporny"
  },
  "SpecialOrganization" : {
      "name" : "somebody"
  }
}
```

then is it so that the second occurence of "SpecialOrganization" will _not_ fail because I used "SpecialOrganization" as a term this time?

**Comment by pchampin** [comment]
I like this new proposal.

If we are to accept it, I would update the spec text, because the paragraph before Example 44 would not be correct anymore. It would have to make it clear why Example 44 works, and in which cases `"@context": null` would fail...

**Comment by dlongley** [comment]
@iherman,

> then is it so that the second occurence of "SpecialOrganization" will _not_ fail because I used "SpecialOrganization" as a term this time?

Yes, it would be legal there. Of course, since `SpecialOrganization` still appears in `@type` in your example, a JSON-LD processor configured to throw errors would have already thrown an error for that occurrence.

**Comment by iherman** [comment]
Would that be an error, like stop processing, or a warning, like ignoring the changes?

Anyway, that is another matter, I think I understand what you are getting at. (Until I am lost again, that is:-) I agree with @pchampin that the text in the spec should be updated asap, to see if the full ~`@seal`~ `@protected` feature can be explained clearly...

**Comment by dlongley** [comment]
> Would that be an error, like stop processing, or a warning, like ignoring the changes?
> 
> Anyway, that is another matter, I think I understand what you are getting at.

I agree that's another issue. I suspect we might want processors to support two modes: a default mode that raises an error (stops processing) and an optional mode to instead issue a warning that the attempted changes were invalid and thus ignored.

**Comment by azaroth42** [comment]
I disagree that the definition provided matches the examples. You can have scoped contexts based on `@type`, so the SpecialOrganization example should NOT fail. Otherwise you're introducing even more special cases by allowing property scoped contexts to override `@protected` but type scoped contexts cannot.

This needs more work.

**Comment by dlongley** [comment]
> You can have scoped contexts based on `@type`, so the SpecialOrganization example should NOT fail.

No, this is not permitted as it would break the protection rules.

> Otherwise you're introducing even more special cases by allowing property scoped contexts to override `@protected` but type scoped contexts cannot.

I disagree. There are not several special cases. There is only *one* way to override `@protected` and it is through property term scoped contexts.

This is chosen because it is the only safe way to do it -- and it matches expectations and intuitions for what "protection" means. The reason `@protection` is added to a term is to enable users to safely consume JSON-LD as regular JSON (i.e. idiomatically and without having to use JSON-LD processing).

Since JSON developers rely on the structure of the JSON tree to understand meaning, it makes sense that adding and removing `@protection` depends on this. Therefore, if `@protection` can be removed, it must only be done in a way that would not break this understanding. Therefore, protection can be safely removed by introducing a new section of the JSON tree via a scoped `@context` -- no other way. This approach mirrors how idiomatic JSON extensions are done: by extending the JSON tree.

**Comment by azaroth42** [comment]
> Since JSON developers rely on the structure of the JSON tree to understand meaning, 

Not necessarily. A perfectly comprehensible JSON pattern would be to instantiate the JSON objects as objects, and then just understand the meaning based on the classes. This would imply that an `@type` based pattern is just as useful as a predicate based pattern.

The special cases are:  
  * `@context: null` doesn't work as one might expect
  * scoped contexts by `@type` don't work as one might expect, and would cause errors when the class is referred to by a predicate scoped context (I believe)

**Comment by dlongley** [comment]
I think an `@type` based pattern is fine, however, when there are conflicts with existing `@protected` terms, processing will fail. You cannot mix types with existing meaning, just like you'd have trouble doing multiple inheritance (or it is prohibited in many languages). So you can't erase existing `@protected` terms using `@type` scoped term definitions.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-04-12-json-ld#section2).

- `RESOLVED:  Allow @protected terms to be changed only via property scoped contexts, and not via setting the active context to null`
- `RESOLVED:  Any attempt to change or clear a @protected term results in an error being raised, other than as provided for already`
<details><summary><i class="differentiate">View the transcript</i></summary>
Additional restriction to @sealed term clearing<br/>
Ivan Herman: link: <a href="https://github.com/w3c/json-ld-syntax/issues/136">https://github.com/w3c/json-ld-syntax/issues/136</a><br/>
Benjamin Young: Protected Term Definition - <a href="https://w3c.github.io/json-ld-syntax/#protected-term-definitions">https://w3c.github.io/json-ld-syntax/#protected-term-definitions</a><br/>
Benjamin Young: we’re discussing 136. There are some already-merged PRs and there are some tests<br/>
… this topic is our exclusive focus for today<br/>
… because this would really help VCWG<br/>
… this piece of work is valuable to support them NOT taking JSON-LD out of the spec<br/>
… let’s start with a summary of the editorial work<br/>
Gregg Kellogg: I think there are some PRs that have been completed on the syntax side<br/>
Pierre-Antoine Champin: all related PRs have been merged<br/>
Gregg Kellogg: I think we still need to add the mechanism that would disallow unsealing via @context:null<br/>
Dave Longley: we’re just looking exactly what gkellogg said<br/>
… what’s currently there would allow for the protection to be removed merely via @context:null anywhere in the doc<br/>
… which doesn’t do what we actually need from the feature<br/>
… the point is to be able to call out terms so that people using the context can be minimal with processing on those terms<br/>
… with but one little change, we can accomplish that<br/>
… just by restricting to a scoped context<br/>
… that will provide the needed assurance<br/>
Pierre-Antoine Champin: to be clear, the @context:null could be on any protected definition?<br/>
Dave Longley: correct<br/>
… should not complicate implementations<br/>
Rob Sanderson: if a @context:null is encountered elsewhere than in a property-scoped context, it changes from wiping out everything to just wiping out non-protected terms?<br/>
Dave Longley: no, that should be an error under our change<br/>
… because that would be trying to remove protection illegally<br/>
Rob Sanderson: that seems backwards-incompatible<br/>
… it changes the meaning of @context:null<br/>
Dave Longley: well, no, because there were never protected terms before<br/>
Rob Sanderson: 2nd opinion would be desirable<br/>
Gregg Kellogg: what we had done before was not throw errors but issue warnings<br/>
David I. Lehn: protectedMode and tests here: <a href="https://github.com/w3c/json-ld-api/pull/69">https://github.com/w3c/json-ld-api/pull/69</a><br/>
Gregg Kellogg: dlehn has an issue for a “protected mode” flag which would switch between errors and warnings<br/>
… are you putting those together or something totally new?<br/>
Dave Longley: we’ve implemented both, and we’re okay with either, but we think that throwing an error would be cleaner, but we can default to the warning<br/>
… and in that case, the protected terms would just not be redefined<br/>
… we have tests for either case<br/>
… but we thought that defaulting to error would be cleaner<br/>
Pierre-Antoine Champin: just wanted to point out that property-scoped context aren’t in 1.0<br/>
… @context:null in a property-scoped definitions simply doesn’t exist now,<br/>
… so we can’t break extant JSON-LD<br/>
… [then changes his mind]<br/>
Gregg Kellogg: the only way to provoke this is via a protected term, which didn’t exist in 1.0<br/>
… so you couldn’t produce this error that way<br/>
… I think that adding flags to the API is waffling<br/>
… we should choose a party to go to<br/>
… in my own processor I run testing in a “validation” mode which is strict<br/>
… this might be such a thing<br/>
… but for conformance, maybe we should just pick a road here<br/>
Rob Sanderson: Here’s when it breaks 1.0: { @context: [ "1.1-context-with-protected", "existing-´1.0-context-with-null"] ... }<br/>
Rob Sanderson: if the intent is that extant 1.0 contexts work as written<br/>
… then adding “protected” that can’t be reset via @context:null<br/>
… won’t work if a 1.0 context began with @context:null but is used at a point where protected terms are in scope<br/>
Gregg Kellogg: it used to be that we run in 1.0 until we see a marker for 1.1, but we now start in 1.1<br/>
Benjamin Young: current processing model triggering definition <a href="https://w3c.github.io/json-ld-syntax/#dfn-processing-mode">https://w3c.github.io/json-ld-syntax/#dfn-processing-mode</a><br/>
Rob Sanderson: so 1.0 contexts still work as expected and danbri won’t come gunning for us?<br/>
… or not?<br/>
… are we going to get objections from Google or MS ?<br/>
… if we can put this into the set of allowable incompatibilities<br/>
… I won’t stand in the way<br/>
Ivan Herman: to prepare for a possible objection, is it worth to add a note to the document making that clear?<br/>
Rob Sanderson: +1 from me to calling it out specifically<br/>
Gregg Kellogg: to say that this is a 1.1 feature?<br/>
Ivan Herman: question may come up, and we can preempt them in this case<br/>
… either in the spec or the best practices doc<br/>
Benjamin Young: if it risks a formal objection we should put it in the docs<br/>
Gregg Kellogg: it’s not necessary to qualify generating an error if the attempt to clear out the context with a protected-mode term in scope for 1.1.<br/>
Adam Soroka: [and I lost the end of the thought]<br/>
Gregg Kellogg: that might be a point at which we could add a note<br/>
… that this error cannot be generated from a proc running in 1.0 mode<br/>
David Newbury: when we’re talking about 1.0 v 1.1 mode for compatibility<br/>
Adam Soroka: .. we’re talking about the doc being processed<br/>
David Newbury: not the context of the context<br/>
Gregg Kellogg: documents aren’t 1.0 or 1.1<br/>
… the processing is 1.0 or 1.1<br/>
… contriolled by @version in the context<br/>
Benjamin Young: the @version definition <a href="https://w3c.github.io/json-ld-syntax/#h-note-1">https://w3c.github.io/json-ld-syntax/#h-note-1</a><br/>
Gregg Kellogg: but that can happen in any context<br/>
David Newbury: right, but that doesn’t change the context, right, just its interpretation in the context (different use of the word) in which it is being processed?<br/>
Rob Sanderson: I understand the pattern of restricting to property-scoped contexts<br/>
… but is that the limit?<br/>
Dave Longley: it’s acceptable to put protected type-scoped definition<br/>
… but you can’t clear terms there<br/>
… that would lead to multiple inheritance<br/>
… think of protected terms as a “base class” for anything in the doc<br/>
… appending a type to any node would change the semantics<br/>
… which misses the whole point, which is to make processing easier<br/>
Rob Sanderson: we can’t limit the types assigned to a resource<br/>
… and type-scoped defns in this way could lead to collisions.<br/>
Gregg Kellogg: I implied something like this in an earlier version<br/>
… what would happen is<br/>
… when you expand based on a property which is a protected term<br/>
… that is when you look for embedded context associated with that term<br/>
… . that is when you could see @contxt:null<br/>
… you detect that by calling expansion with some option that includes the term at hand<br/>
Dave Longley: we ran into no gotchas<br/>
… we did it with both warning and error<br/>
… it was simple, the hardest part was the warning<br/>
… tracking when you can clear protection or not was actually fairly simple<br/>
Gregg Kellogg: ready with a Pull Request?<br/>
Dave Longley: not quite, but quite close<br/>
Benjamin Young: <a href="https://github.com/w3c/json-ld-api/pull/69">https://github.com/w3c/json-ld-api/pull/69</a><br/>
Benjamin Young: Add @protected tests and a protectedMode flag.<br/>
Dave Longley: yeah, that looks like the right PR<br/>
David I. Lehn: the related is implementation PR is here: <a href="https://github.com/digitalbazaar/jsonld.js/pull/289">https://github.com/digitalbazaar/jsonld.js/pull/289</a><br/>
Pierre-Antoine Champin: I can edit the current section on “protected” in the syntax document, to reflect those changes<br/>
Dave Longley: that PR should cover all the bases<br/>
… clearing things when you should be bale to, when you shouldn’t…<br/>
Gregg Kellogg: some updates look to be needed<br/>
… some test are failing and it’s coming from Digital Bazaar’s repo<br/>
Dave Longley: we can move the PR, np<br/>
Benjamin Young: this PR has the protected mode warning/error flag on the API<br/>
… we can massage that independent of the PR<br/>
Ivan Herman: firstly we should formally resolve the issue in a very clear way<br/>
… but also we need a statement or something from this WG making it clear that this is a feature that is frozen and will not be removed<br/>
Dave Longley: yes, we need that reassurance<br/>
Ivan Herman: we have to produce that<br/>
… a similar situation (JSON-LD being behind) can happen with WoT WG as well<br/>
… they will need the same kind of things<br/>
… we could produce a blog<br/>
… saying that all features in the document are stable in the sense that<br/>
… we don’t expect to remove them<br/>
… would that work for you?<br/>
Dave Longley: my understanding is that it would<br/>
Gregg Kellogg: when we talked about freezing before, I said then that we need to get out a WD<br/>
… I don’t think we can point at an editor’s draft for such an assurance<br/>
… so what’s the timing for that?<br/>
Ivan Herman: for a CR, for which you are running right now<br/>
… having a fresh WD from JSON-LD WG should be enough<br/>
… but getting to Rec would mean that isn’t enough<br/>
… we have a publishing process through which to go, and it could take 2-3 weeks<br/>
Dave Longley: We’re already in CR<br/>
… 2-3 weeks doesn’t change anything<br/>
… we prefer sooner rather than later<br/>
… this will help us get through a number of issues<br/>
Ivan Herman: and helps you with the discussion you are having with commenters<br/>
Rob Sanderson: let’s say we have a WD within 1-2 weeks<br/>
… and get the feedback<br/>
… then write the blog post saying “No more new features”<br/>
… would be 3-4 weeks<br/>
Dave Longley: yes, but TBC all we need is “these features won’t be taken out”, not “no new features”<br/>
Rob Sanderson: if we do hit timeline issues, we could offer something more than a blog post for VCWG in particular<br/>
Dave Longley: a simple statement would be acceptable<br/>
Gregg Kellogg: we do need to resolve “warnings vs. errors”<br/>
Rob Sanderson: we need to discuss that beforehand<br/>
Dave Longley: I don’t want to prevent people from writing nonstandard implementations that use warnings,<br/>
… I was concerned by not having this behavior be configurable<br/>
Proposed resolution: attempts to override @protected terms will throw an error during processing in 1.1 mode (Benjamin Young)<br/>
Adam Soroka: +1<br/>
Adam Soroka: me oh, good point<br/>
Adam Soroka: [general discussion about how to advance the wording of this propsoal]<br/>
Dave Longley: don’t want to confuse people with wording about when you can use @context:null<br/>
Gregg Kellogg: also, terms aren’t really changed by that action, they are cleared<br/>
… @context:null doesn’t change terms, it clears them<br/>
Rob Sanderson: I thought you didn’t need to set @context:null to alter a term<br/>
Gregg Kellogg: what if you set a term defintion to null?<br/>
Rob Sanderson: we can put that off until later<br/>
Rob Sanderson: {"@context": {"protected": {"@id": "something", "@protected": True}, "extension": {"@context": {"protected": {"@id": "something else"}}}<br/>
Rob Sanderson: I believe that given our current definitions, that ^^^ would be acceptable<br/>
… you should be able to set a term directly to something else<br/>
Dave Longley: as long as you are property-scoped, you can wipe out everything, but yes, you could go at only a single term<br/>
Gregg Kellogg: and 1.0 does allow setting a single term to null<br/>
Proposed resolution: Allow @protected terms to be changed only via property scoped contexts, and not via setting the active context to null (Benjamin Young)<br/>
Dave Longley: +1 (of course, setting the context to null within a property scoped context is also allowed)<br/>
Gregg Kellogg: +1<br/>
Rob Sanderson: +1<br/>
Rob Sanderson: we could make that a bit clearer as pointed out by dlongely<br/>
Jeff Mixter: +1<br/>
Benjamin Young: +1<br/>
David Newbury: +1<br/>
Ivan Herman: +1<br/>
Pierre-Antoine Champin: +1<br/>
Tim Cole: +1<br/>
Ruben Taelman: +1<br/>
David I. Lehn: +1<br/>
Adam Soroka: +1<br/>
Resolution #2: Allow @protected terms to be changed only via property scoped contexts, and not via setting the active context to null<br/>
Adam Soroka: the proposal, just the text; I am on board with the idea<br/>
Gregg Kellogg: other than as previously provided<br/>
Dave Longley: +1 to Gregg<br/>
Dave Longley: +1 to the proposal<br/>
Benjamin Young: what we’re saying is that it is indeed an error, not a warning<br/>
Ivan Herman: +1<br/>
Proposed resolution: Any attempt to change or clear a @protected term results in an error being raised, other than as provided for already (Rob Sanderson)<br/>
David Newbury: +1<br/>
Gregg Kellogg: +1<br/>
Jeff Mixter: +1<br/>
Rob Sanderson: +1<br/>
Adam Soroka: +1<br/>
Dave Longley: +1<br/>
Ivan Herman: +1<br/>
Tim Cole: +1<br/>
Pierre-Antoine Champin: +1<br/>
Ruben Taelman: +1<br/>
Benjamin Young: +1<br/>
David I. Lehn: +1<br/>
Resolution #3: Any attempt to change or clear a @protected term results in an error being raised, other than as provided for already<br/>
Gregg Kellogg: for the purpose of best time use we should look at issues on the GitHub management console to find what we need to do to get to a new WD<br/>
Ivan Herman: different topic?<br/>
Benjamin Young: yeah, I have no other issues<br/>
</details>
