### ISSUE TITLE
Suggestion: Expected behavior for profile URIs not listed in Appendix C?

### ISSUE THREAD

**Issue by swickr** [w3c/json-ld-syntax#170]
The specification of [application/ld+json](https://www.w3.org/TR/2018/WD-json-ld11-20181214/#iana-considerations) defines three profile URIs.   The expected behavior when some other URI is given appears to be unspecified.

If JSON-LD  were to specify that

- JSON-LD 1.1 processors should ignore (*) any other URI appearing in a profile parameter and
- profile URIs matching http://www.w3.org/ns/json-ld* are explicitly reserved for future JSON-LD specifications

this would provide an additional point of extensibility.

(*) behave as if that URI were not present

**Comment by gkellogg** [comment]
Thanks @swickr. I agree in reserving the `json-ld*` namespace for this specification. But, other profile IRIs may be used by other specifications to define behavior specific to their use cases, which some processors may recognize. We should word your first point to allow for such extensions.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-06-07-json-ld.html#section3-1).

- `RESOLVED:  Accept #170, with the clarification that processors MUST ignore IRIs that that they do not recognize, and that json-ld IRIs are reserved for future WG use*`
- `ACTION:  update syntax with issue #170 resolution (Pierre-Antoine Champin)`
<details><summary><i class="differentiate">View the transcript</i></summary>
3.1. Profile IRIs<br/>
Ivan Herman: <a href="https://github.com/w3c/json-ld-syntax/issues/170">https://github.com/w3c/json-ld-syntax/issues/170</a><br/>
Ivan Herman: one background - transition calls with WOT people<br/>
… they were interested in a profile for their own needs<br/>
… but what came up is what is policy with regard to what is said in W3C documents<br/>
… by default each WG has its own profile space (e.g., ns/jsonld…)<br/>
… and that’s it<br/>
Rob Sanderson: there are profile URIs (e.g., Web Annotation)<br/>
… if you don’t understand it, you must ignore it<br/>
Proposed resolution: Accept #170, with the clarification that processors MUST ignore IRIs that that they do not recognize, and that json-ld* IRIs are reserved for future WG use (Rob Sanderson)<br/>
Rob Sanderson: +1<br/>
Adam Soroka: +1<br/>
Tim Cole: +1<br/>
Ruben Taelman: +1<br/>
Ivan Herman: +1<br/>
Benjamin Young: +1<br/>
Pierre-Antoine Champin: +1<br/>
David I. Lehn: +1<br/>
David Newbury: +1<br/>
Resolution #2: Accept #170, with the clarification that processors MUST ignore IRIs that that they do not recognize, and that json-ld IRIs are reserved for future WG use*<br/>
Rob Sanderson: Action to implement this resolution is on pchampin or greg<br/>
Action #1: update syntax with issue #170 resolution (Pierre-Antoine Champin)<br/>
</details>

**Comment by iherman** [comment]
Settled in #193. @swickr, the proposal has been accepted and has been put into the editor's draft.

Closing the issue
