### ISSUE TITLE
keyword aliases for @id and @type cannot be singly @protected?

### ISSUE THREAD

**Issue by azaroth42** [w3c/json-ld-syntax#246]
In section 4.1.5 (and equivalent in the algorithm) it says that aliases applied to keywords are ignored, other than (per 4.3.3) the use of `@container:@set` applied to `@type`.

However, the `@protected` keyword can be applied to keyword aliases by setting it in the context overall. This is at odds with the text, and prevents protecting ONLY the (very common, and important) aliases for `@id` and `@type`. 

Propose (I know, 11th hour) that `@protected` be allowed as an entry for keyword aliases (unless we already discussed this and decided against it, and I'm just forgetting). We can already protect them, just by the syntactic sugar form of setting it at the context level.

**Comment by azaroth42** [comment]
Works as expected:
```
{
  "@context": {
    "@protected": true,
    "id": "@id"
  },
  "id": "http://example.com/1"
}
```

Does not work, as `@protected` is ignored for aliases of keywords:

```
{
  "@context": {
    "id": {"@id": "@id", "@protected": true}
  },
  "id": "http://example.com/1"
}
```

**Comment by azaroth42** [comment]
Also, the syntax is inconsistent with the API definition.

Syntax says that the definitions will be ignored, whereas API says "Any other value means that a keyword redefinition error has been detected and processing is aborted." 

The API is the correct intention, and the syntax document should be updated to this effect.

**Comment by azaroth42** [comment]
Changing to editorial as the algorithm is in -api, not -syntax

**Comment by azaroth42** [comment]
@gkellogg  to look through other normative sections to ensure consistency

**Comment by azaroth42** [comment]
Resolution: Allow the use of `@protected` as a valid keyword in term definitions which are aliases of keywords or where the term is `@type`.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-09-19-json-ld#section3-2).

- `RESOLVED:  Allow the use of <code>@protected</code> as a valid keyword in term definitions which are aliases of keywords or where the term is <code>@type</code>`
<details><summary><i class="differentiate">View the transcript</i></summary>
keyword alias for <code>@id</code> and <code>@type</code> cannot be singly <code>@protected</code><br/>
Benjamin Young: See Syntax issue 246<br/>
Rob Sanderson: if you alias <code>@type</code> to type it can still be a set<br/>
… however, using <code>@protected</code> on an object-based term definition will not protect the id aliasing<br/>
… so my proposal is that we change <code>@protected</code> to be a legal keyword for keyword aliases<br/>
Gregg Kellogg: does <code>@protected</code> protect the <code>@type</code> based aliasing?<br/>
Rob Sanderson: [adds more examples to 246]<br/>
Ivan Herman: the examples don’t show any reason for the <code>@protected</code><br/>
Rob Sanderson: [fixes examples]<br/>
… [reads text from 4.1.5]<br/>
… [reads text from 4.3.3]<br/>
Gregg Kellogg: looks like the API is correct<br/>
Rob Sanderson: ah, so they’re out of sync<br/>
Gregg Kellogg: we do need more <code>@protected</code> text in this API section<br/>
Rob Sanderson: so the syntax fix is editorial<br/>
Proposed resolution: Allow the use of <code>@protected</code> as a valid keyword in term definitions which are aliases of keywords or where the term is <code>@type.</code> (Rob Sanderson)<br/>
Rob Sanderson: +1<br/>
Gregg Kellogg: +1<br/>
Benjamin Young: +1<br/>
Pierre-Antoine Champin: +1<br/>
Ivan Herman: +1<br/>
Resolution #2: Allow the use of <code>@protected</code> as a valid keyword in term definitions which are aliases of keywords or where the term is <code>@type</code><br/>
</details>

**Comment by gkellogg** [comment]
I added the syntax change in cfd32c665fd728ed5198bdf9c3ad606723074a27, but intended to do a PR. Can't easily undo that, so please check it out and see if the change is reasonable.

**Comment by gkellogg** [comment]
WG [resolved to close the issue as complete](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-10-18-json-ld#resolution2).
