### ISSUE TITLE
Use of null value with JSON literals

### ISSUE THREAD

**Issue by azaroth42** [w3c/json-ld-syntax#258]
Typically the null value removes the property or resets a context. However JSON literals capture any legal JSON value, which includes null.

Thus there is ambiguity currently as to the expected result of a property with a JSON literal typed value where the `@value` is null.  Current implementations are inconsistent between compact and expanded form, and thus there is missing text in the algorithm to preserve null when the type is `@json`.

```
{
  "@context": {
    "@version": 1.1,
    "property": {"@id": "rdfs:label", "@type": "@json"}
  },
  "property": null
}
```

**Comment by azaroth42** [comment]
RESOLUTION:  WG believes that it is least surprising to process null as a JSON literal in this case, and not to remove the property in the internal representation, and thus the null should be preserved.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-09-19-json-ld#section3-1).

- `RESOLVED:  WG believes that it is least surprising to process null as a JSON literal in this case, and not to remove the property in the internal representation, and thus the null should be preserved.`
<details><summary><i class="differentiate">View the transcript</i></summary>
Use of null value with JSON literals<br/>
Rob Sanderson: See Syntax Issue #258<br/>
Gregg Kellogg: in most statements we do not include the nulls. one exception is JSON literals<br/>
… but null is a valid JSON value, so there are reasons to keep them<br/>
… pchampin pointed out a similar situation with strings, but that was an implementation issue<br/>
… but it did help us find this<br/>
… you can keep the null value currently by using the <code>@type:</code> <code>@json</code><br/>
… but in other cases we take it out<br/>
… so we’re at least inconsistent<br/>
… it implies that there’s some missing algorithm text<br/>
… for preserving a key/value with a value of null<br/>
… there are various options for preserving them<br/>
… we could also decide not to<br/>
… but I do think we can<br/>
… if you expand it, and then re-expand it the null goes away…even when using the <code>@json</code> value type<br/>
… it’s an editorial issue once we figure out how we want to handle it<br/>
… because it’s a lack of clarity<br/>
… should be the work of an hour or two<br/>
Rob Sanderson: the question then is should the null be treated as a JSON literal null or should we remove the property<br/>
Benjamin Young: Apache CouchDB and MongoDB (iirc) will remove keys set to null<br/>
Rob Sanderson: that’s what this does in every other case…except the new <code>@json</code> type<br/>
… I think it’s more surprising for the null to go away if the type is <code>@json</code> than for it to stay around<br/>
… but…do we want to still provide a way to remove the key/value?<br/>
Ivan Herman: why would we want to remove key/values?<br/>
Benjamin Young: databases do it<br/>
Rob Sanderson: but this would be full statements<br/>
Gregg Kellogg: so most of the testing I’ve done was with numeric values and objects<br/>
Benjamin Young: is null on it’s own a valid JSON value/document?<br/>
… what would JSON.parse do?<br/>
Gregg Kellogg: it would keep it<br/>
Pierre-Antoine Champin: I’m playing around with the code right now, and gkellogg mentioned that re-expansion would get rid of it<br/>
… I added the <code>@version:</code> 1.1<br/>
… otherwise it doesn’t work at all<br/>
… and when I do it, it looks like we get an invalid value<br/>
Gregg Kellogg: part of the use of null is to eliminate contexts<br/>
… you can certainly handle these by setting a 1.1 at the processor level–if the document itself doesn’t set it<br/>
Rob Sanderson: azaroth tests JSON.parse("null") in chrome, and the result is a real null<br/>
Gregg Kellogg: but you’re right it could be restricted to 1.0-based processing<br/>
… so we may need to update tests to use 1.1 mode<br/>
… and test with expanded values<br/>
… so setting the processing mode is probably the way to do it<br/>
Proposed resolution: WG believes that it is least surprising to process null as a JSON literal in this case, and not to remove the property in the internal representation, and thus the null should be preserved. (Rob Sanderson)<br/>
Rob Sanderson: +1<br/>
Ivan Herman: +1<br/>
Benjamin Young: +1<br/>
Gregg Kellogg: +1<br/>
Pierre-Antoine Champin: +1<br/>
Resolution #1: WG believes that it is least surprising to process null as a JSON literal in this case, and not to remove the property in the internal representation, and thus the null should be preserved.<br/>
David I. Lehn: +1<br/>
</details>

**Comment by gkellogg** [comment]
Actually, I don't think there's anything more to say in the syntax document. It's handled in w3c/json-ld-api#155. Happy to add some extra wording to the syntax document if people think it necessary.

**Comment by azaroth42** [comment]
I think there should be a non-normative note in syntax, in 4.2.2, as there is a potential expectation that nulls will not be processed, as with other cases.

**Comment by iddan** [comment]
Why is `null` not converted to `rdf:nil`?

**Comment by rubensworks** [comment]
> Why is null not converted to rdf:nil?

`rdf:nil` is not equivalent to `null`. `rdf:nil` is used to indicate the end of an RDF list.
The [spec](https://www.w3.org/TR/rdf-schema/#ch_nil) says the following:

> The resource rdf:nil is an instance of rdf:List that can be used to represent an empty list or other list-like structure.

**Comment by iddan** [comment]
Oh, my bad. Thank you.

**Comment by azaroth42** [comment]
Also, this is specifically about JSON literals, where the JSON values are intentionally left as JSON rather than mapped into RDF.
