### ISSUE TITLE
@vocab's presence causes @foo in a value object to fail, otherwise it doesn't

### ISSUE THREAD

**Issue by azaroth42** [w3c/json-ld-syntax#259]
The following fails, as expected, but only due to the presence of `@vocab`.

```
{
  "@context": {
     "@vocab": "https://schema.org/"
  },
  "name": {
    "@value": "fish",
    "@language": "en",
    "@direction": "ltr"
  }
}
```

However the following ignores the `@direction` property:

```
{
  "@context": {
     "name": "https://schema.org/name"
  },
  "name": {
    "@value": "fish",
    "@language": "en",
    "@direction": "ltr"
  }
}
```

This bug exists in both JSON-LD 1.0 and 1.1

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-09-20-json-ld#section5-3).

- `RESOLVED:  Close w3c/json-ld-syntax#259 as we can’t fix 1.0, and 1.1 will be solved by newly reopened #16`
<details><summary><i class="differentiate">View the transcript</i></summary>
Ivan Herman: See Issue syntax#16<br/>
Rob Sanderson: propose that we can close #259, is this errata to JSON-LD 1.0?<br/>
Gregg Kellogg: it’s not<br/>
Rob Sanderson: Ok, this will remain a bug with 1.0 processors, they should update and do the 1.1 process for this particular feature.<br/>
Proposed resolution: Close w3c/json-ld-syntax#259 as we can’t fix 1.0, and 1.1 will be solved by newly reopened #16 (Rob Sanderson)<br/>
Rob Sanderson: +1<br/>
Ivan Herman: +1<br/>
Manu Sporny: +1<br/>
Pierre-Antoine Champin: +1<br/>
Simon Steyskal: +1<br/>
Gregg Kellogg: +1<br/>
Benjamin Young: +1<br/>
Resolution #6: Close w3c/json-ld-syntax#259 as we can’t fix 1.0, and 1.1 will be solved by newly reopened #16<br/>
5<br/>
</details>
