### ISSUE TITLE
Named Graphs: confusing "embedding doesn't work as each node object references the other"

### ISSUE THREAD

**Issue by Fak3** [w3c/json-ld-syntax#300]
There is a confusing line in the 4.9 Named Graphs section: https://github.com/w3c/json-ld-syntax/blob/master/index.html#L9157 It says: 
> In this case, embedding doesn't work as each node object references the other. 

But above, in the [example 94](https://www.w3.org/TR/json-ld11/#example-94-referencing-an-unidentified-node) the same case is given with embedding working just fine with blank node id. 

This is confusing, because i have an impression that by replacing blank node identifier with a regular iri ("http://manu.sporny.org/about#manu" ) this example shows that embedding works here just fine.

If I am missing something, perhaps it worth a rewording?

**Comment by pchampin** [comment]
Example 94 does not rely *only* on embedding; the inner "knows" property uses an ID reference, rather than embedding the full description of Manu Sporny...

But you are right:
*  the sentence you quote may give the impression that cycles prevent *entirely* the use of embedding, which is obviously not the case,
* the [example 115](https://w3c.github.io/json-ld-syntax/#example-115-using-graph-to-explicitly-express-the-default-graph) is not a compelling use case for the top level `@graph`, as it can be expressed without it, as [example 94](https://w3c.github.io/json-ld-syntax/#example-115-using-graph-to-explicitly-express-the-default-graph) demonstrates.

I suggest that
* we remove the `knows` properties from example 115,
* we rephrase the sentence into something like "embedding does not work as the graph contains unrelated nodes" (which is a better caracterisation of the situations where a top-level `@graph` is strictly required).

**Comment by Fak3** [comment]
Yes, that clarifies the case for me

**Comment by azaroth42** [comment]
Resolved :)
