### ISSUE TITLE
@context as relative IRI

### ISSUE THREAD

**Issue by hsolbrig** [w3c/json-ld-syntax#311]
The specification says that an `@context` can be an `IRI reference`, meaning that it can be an absolute _or_ a relative IRI.  Questions:
1) If relative, is it resolved against the document base?
2) Why doesn't this appear to work in the playground?
(see: http://tinyurl.com/u6z4ot7 for one attempt)

**Comment by gkellogg** [comment]
It is relative to the document in which it is contained. It should work properly in jsonld.js, but in the embedded context of the playground, this may not be apparent.

**Comment by hsolbrig** [comment]
Is it document relative only, or can it be changed with '@base'?

**Comment by gkellogg** [comment]
There are tests for this, and I believe it does not consider `@base`.

**Comment by gkellogg** [comment]
5.2 of the [Context Processing Algorithm](https://www.w3.org/TR/json-ld11-api/#algorithm) makes this pretty clear:

> Initialize context to the result of resolving context against the base IRI of the document containing the local context which is established 

It's detailed enough, and I don't think we really need to burden the syntax document with this much detail.

**Comment by ericprud** [comment]
I tried some pretty trivial tests with a JSON-LD doc which referenced another:
``` json
{ "@context": "http://localhost/tmp/npmz/jsonld-user/outer.jsonld",
  "outer": { "inner": "http://inner/" } }
```
which in turn referenced another:
``` json
{ "@context": {  "@version": 1.1,
    "outer": {
      "@id": "foo:outer",
      "@context": "http://localhost/tmp/npmz/jsonld-user/inner.jsonld"
    } } }
```
(both served as "application/ld+json")
This worked as long as the URLs were absolute but not when I changed e.g. that 2nd to have an @context of either "inner.jsonld" or  "/tmp/npmz/jsonld-user/inner.jsonld".
Should this be covered by the tests?

**Comment by gkellogg** [comment]
I thought we had a test for this from 1.0, but I don't see one, so something like this is certainly necessary.

**Comment by hsolbrig** [comment]
> 5.2 of the [Context Processing Algorithm](https://www.w3.org/TR/json-ld11-api/#algorithm) makes this pretty clear:
> 
> > Initialize context to the result of resolving context against the base IRI of the document containing the local context which is established
> 
> It's detailed enough, and I don't think we really need to burden the syntax document with this much detail.

While there is definitely detail that is irrelevant to JSON-LD end user, I don't see this question falling into that category.  Where we are today, the syntax document appears be _the_ document that json-ld users would go to to answer questions about how the language is used and interpreted.  Less than ideal, I know, but requiring someone to have consumed all _three_ specifications before being able to use JSON-LD in anger is asking an awful lot.

**Comment by ericprud** [comment]
> I thought we had a test for this from 1.0, but I don't see one, so something like this is certainly necessary.

The above pull provides one which is the only test for:
1. @context referenced @context
2. @context with relative URLs

I created an analogous remote test but a PR on that will fail until it gets merged as it relies on `https://w3c.github.io/json-ld-api/tests` .

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-12-06-json-ld#section4-1).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
Benjamin Young: Next three issues are all marked as editorial<br/>
Benjamin Young: <a href="https://github.com/w3c/json-ld-syntax/issues/311">https://github.com/w3c/json-ld-syntax/issues/311</a><br/>
Benjamin Young: don’t need much more than an overview of the issues<br/>
… this one was from Harold …<br/>
Harold Solbrig: This started out as a question, as it wasn’t clear to me in the docs, where context can be a relative URI as to what it’s resolution base is<br/>
… Eric Prud’hommeaux has code that resolves against an outer context<br/>
… we hope that it remains that way – that the inner context is done in terms of the outer context – as we’re building a bunch of fragmentary contexts, and don’t want to have to put in absolute URIs as that’s painful to maintain<br/>
Gregg Kellogg: I recalled that we settled in 1.0 but didn’t find a test for it<br/>
… Eric submitted one, I tweaked and it found a bug<br/>
… you shouldn’t regard @base as a logical not a physical location. If you load from a document, it should be from that physical location<br/>
… or from a URI it would be from where it was retrieved from<br/>
… writing the test found issues … we need to clarify the processing in t he syntax document, not the API doc<br/>
… as that’s where authors writing contexts will be looking<br/>
Benjamin Young: Is there some question here that needs to be resolved?<br/>
Ivan Herman: Change to the doc, or just the tests?<br/>
Gregg Kellogg: syntax doc isn’t explicit enough about how they’re resolved<br/>
… informative text in any case, that describes how this happens<br/>
Rob Sanderson: the normative text is in the algorithm in API and is already correct?<br/>
Gregg Kellogg: Yes, if the context is a relative IRI, then it is resolved with respect to the location of the containing document, rather than the base<br/>
Harold Solbrig: if I understand eric’s example, the context is resolved against the outer one.<br/>
Gregg Kellogg: Yes, the same thing. If you resolve a relative IRI context, it’s resolved relative to the document that contains the reference<br/>
… so embedded in a context or in a document, it/s the same<br/>
Harold Solbrig: This would be nice to know without reading the API, so good to have in the syntax doc<br/>
</details>
