### ISSUE TITLE
advice on what to do when encountering @protected terms (vcdm/as2)

### ISSUE THREAD

**Issue by gobengo** [w3c/json-ld-syntax#424]
Take this example JSON-LD.
[it appears to be erroneous do to the `mediaType` property being protected in the outer context, and trying to be redefined in the inner context](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22type%22%3A%5B%22VerifiableCredential%22%5D%2C%22credentialSubject%22%3A%7B%22%40context%22%3A%5B%22https%3A%2F%2Fwww.w3.org%2Fns%2Factivitystreams%22%5D%2C%22type%22%3A%5B%22Organization%22%5D%2C%22icon%22%3A%7B%22type%22%3A%22Link%22%2C%22mediaType%22%3A%22image%2Fpng%22%7D%7D%2C%22%40context%22%3A%5B%22https%3A%2F%2Fwww.w3.org%2Fns%2Fcredentials%2Fv2%22%5D%7D)

The outer context from `"https://www.w3.org/ns/credentials/v2"` defines a `mediaType` term as `@protected` and with a different IRI as the context inside the credentialSubject which is ActivityStreams2.

If possible, I'd love for the JSON serialization of the credentialSubject.icon.mediaType to map to `https://www.w3.org/ns/activitystreams#mediaType` but still use the JSON key `mediaType`.

This is the first time I've encountered `@protected` terms, so I'm trying to grok what my options are.

After tinkering around a bit, I think it might not be possible to do what I want.
(so, for now, when I try to make this JSON-LD, I compact the credentialSubject with a context like `{ "as": "https://www.w3.org/ns/activitystreams#" }`, but then of course I lose `credentialSubject.icon.mediaType` and get `credentialSubject.icon["as:mediaType"]`.

I also [tried][try-1] to insert a `null` in the `credentialSubject["@context"]` array, but I think that isn't allowed at least by jsonld.js (which I assume is pretty faithful to the spec).

```json
{
  "type": [
    "VerifiableCredential"
  ],
  "credentialSubject": {
    "@context": [
      "https://www.w3.org/ns/activitystreams"
    ],
    "type": [
      "Organization"
    ],
    "icon": {
      "type": "Link",
      "mediaType": "image/png"
    }
  },
  "@context": [
    "https://www.w3.org/ns/credentials/v2"
  ]
}
```

[try-1]: https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22type%22%3A%5B%22VerifiableCredential%22%5D%2C%22credentialSubject%22%3A%7B%22%40context%22%3A%5Bnull%2C%22https%3A%2F%2Fwww.w3.org%2Fns%2Factivitystreams%22%5D%2C%22type%22%3A%5B%22Organization%22%5D%2C%22icon%22%3A%7B%22type%22%3A%22Link%22%2C%22mediaType%22%3A%22image%2Fpng%22%7D%7D%2C%22%40context%22%3A%5B%22https%3A%2F%2Fwww.w3.org%2Fns%2Fcredentials%2Fv2%22%5D%7D

**Comment by Fak3** [comment]
Related to #361

**Comment by dlongley** [comment]
Here is an option that is based off of [Example 2](https://www.w3.org/TR/activitystreams-core/#jsonld) from the Activity Streams spec, which looks like this:

```json
{
  "@context": {
     "@vocab": "https://www.w3.org/ns/activitystreams",
     "ext": "https://canine-extension.example/terms/",
     "@language": "en"
  },
  "summary": "A note",
  "type": "Note",
  "content": "My dog has fleas.",
  "ext:nose": 0,
  "ext:smell": "terrible"
}
```

You can do this:

```json
{
  "@context": [
    "https://www.w3.org/ns/credentials/v2",
    {
      "@vocab": "https://www.w3.org/ns/activitystreams#",
      "icon": {
        "@id": "https://www.w3.org/ns/activitystreams#icon",
        "@type": "@id",
        "@context": {
          "mediaType": "https://www.w3.org/ns/activitystreams#mediaType"
        }
      }
    }
  ],
  "type": [
    "VerifiableCredential"
  ],
  "credentialSubject": {
    "type": [
      "Organization"
    ],
    "icon": {
      "type": "Link",
      "mediaType": "image/png"
    }
  }
}
```

Playground link: http://tinyurl.com/yvhnf7vr

Note that protected terms can only be overridden when a new term definition is provided with a scoped context -- such that the terms being overridden will be scoped to that new term only. This ensures that consumers can have confidence in the definitions being used based on the structure of the JSON tree.

If you wanted to bring in the entire AS context you could also do so using `@import`, but there's currently a bug with the playground that disallows it because it thinks that the `@vocab` keyword itself (from the AS context) is being redefined (and you can't ever redefine keywords). Once fixed this should also work:

```json
{
  "@context": [
    "https://www.w3.org/ns/credentials/v2",
    {
      "@import": "https://www.w3.org/ns/activitystreams",
      "mediaType": {
        "@id": "https://schema.org/encodingFormat"
      },
      "icon": {
        "@id": "https://www.w3.org/ns/activitystreams#icon",
        "@type": "@id",
        "@context": {
          "mediaType": "https://www.w3.org/ns/activitystreams#mediaType"
        }
      }
    }
  ],
  "type": [
    "VerifiableCredential"
  ],
  "credentialSubject": {
    "type": [
      "Organization"
    ],
    "icon": {
      "type": "Link",
      "mediaType": "image/png"
    }
  }
}
```

http://tinyurl.com/33fyyeuf

This approach does an "inline edit" of the AS v2 context via the `@import` feature to fix up the offending definition (`mediaType`) and adds the AS alternative definition for it when it is nested within `icon`.

So there should be a few options here to cause the output to behave properly. Ideally, I think, someone would construct a more modern activity streams context that uses scoped contexts to isolate definitions for usage with other documents  types such as VCs. Alternatively, `@vocab` could be relied on as in the first working example here.

**Comment by gobengo** [comment]
@dlongley Thank you, Dave. This looks extremely helpful. I did see in spec text that there may be an affordance for this, but couldn't figure it out in the playground. Sounds like maybe I didn't do the right incantation. Will try it out and get back to you here. tysm!

**Comment by davidlehn** [comment]
Another possible path is to define a property with a scoped context and use that in `credentialSubject`.  Shown here with an inline context, but this could be put in a small https://www.w3.org/ns/activitystreams-vc context if the only use of AS properties is under the special property.  I think the output n-quads are what one would expect.  There may be some variations of this.

```json
{
  "@context": [
    "https://www.w3.org/ns/credentials/v2",
    {
      "BIKESHED": {
        "@id": "https://www.w3.org/ns/activitystreams#credential",
        "@type": "@id",
        "@context": "https://www.w3.org/ns/activitystreams"
      }
    }
  ],
  "type": [
    "VerifiableCredential"
  ],
  "credentialSubject": {
    "BIKESHED": {
      "type": [
        "Organization"
      ],
      "name": "imaorg",
      "icon": {
        "type": "Link",
        "mediaType": "image/png"
      }
    }
  }
}
```
https://tinyurl.com/253tu643

Pros:
- Can be made short and minimal compared to alternatives.
- Skips the tricky overrides.

Cons:
- Needs extra setup.
- Needs a special top-level property.

**Comment by gobengo** [comment]
I have the advice I was originally looking for now. tysm all
