### ISSUE TITLE
Allow relative IRIs for @vocab

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-syntax#72]
JSON-LD separates handling of IRI conversions for document- and vocabulary-relative IRIs. At times, it is useful to have more vocabulary items be considered in the document space. A change was made to allow the empty string ("") as a value for `@vocab`, but this may not be adequate.

Issue #56 somewhat complains about this, as does #37.

Currently, the Syntax document describes this in [§4.1.2.1 Using the Document Base as the Default Vocabulary](https://www.w3.org/TR/json-ld11/#using-the-document-base-as-the-default-vocabulary), but the use of a term `"#breweats"` is not a natural JSON property. If `@vocab` could be set to `"#"`, this would allow a more natural expression.

The API document has a carve-out for the empty string, but otherwise require `@vocab` to resolve to an absolute IRI:

> Otherwise, if value is an _absolute IRI_ or _blank node identifier_, the vocabulary mapping of result is set to value. If it is not an _absolute IRI_, or a _blank node identifier_, an `invalid vocab mapping` error has been detected and processing is aborted.

The proposal would be to treat things that are not absolute IRIs as IRIs relative to the document base as does the current empty-string carveout:

> Otherwise, if value the empty string (""), the effective value is the current _base IRI_.

Resolving vocabulary-relative IRIs is done with simply concatenation, so the proposal would be to concatenate any non-absolute IRI value of `@vocab` to _base IRI_ by concatenating the value of `@vocab` to _base IRI_; if the result is not then a valid _absolute IRI_ we would continue to generate an `invalid vocab mapping` error. Note that this sill not invalidate any 1.0 documents, but will allow things which were previously not valid.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-10-26-json-ld#section3).

- `RESOLVED:  Allow IRIs to be constructed by string concatenation with multiple @vocabs, with appropriate security consideration section`
- `ACTION:  Rob Sanderson to make a security consideration issue re relative IRI concatenation`
- `ACTION:  Rob Sanderson to create security consideration re javascript URIs and relative IRIs`
<details><summary><i class="differentiate">View the transcript</i></summary>
Gregg Kellogg: in JSON-LD, vocab-relative and document-relative IRIs are resolved differently. we’ve already looked at this problem<br/>
… and offered the ability to set @vocab=""<br/>
… which allows vocab to be resolved against the document base<br/>
… motivated at least in part because in other RDF formats, that distinction doesn’t exist<br/>
… so there was a parity issue against other serializations<br/>
… this issue goes further, and lets @vocab get set to any relative URI, which would then be evaluated against the document base<br/>
… the proposal includes that if a @vocab is already set and a new relative @vocab comes along, one simply string-appends the new one to the old one<br/>
Rob Sanderson: in the case of a base that came from HTTP with a # on the end, that would get lost<br/>
Gregg Kellogg: this also addresses the problem that Manu raised in the context of blank-node-properties.<br/>
Rob Sanderson: if you set vocab to ../# and you had example.org/ns then you get example.org/ns../#<br/>
Ivan Herman: as an editorial matter we must make very clear that this is string concatenation, not IRI concatenation<br/>
<b>rob:</b> are there good rules for determining relative vs. absolute IRIs?<br/>
Ivan Herman: Look for the scheme<br/>
Ivan Herman: I am almost sure that the URI spec defines that very clearly<br/>
Rob Sanderson: but this could be a security problem if a malicious actor sets a CURI prefix of “http” to some malicious address<br/>
Ivan Herman: also the same thing with base<br/>
Gregg Kellogg: We can’t really know<br/>
Rob Sanderson: we can just advise people of the security concerns<br/>
Action #1: Rob Sanderson to make a security consideration issue re relative IRI concatenation<br/>
Ivan Herman: do we check for “acceptable” scheme?<br/>
… what about Javascript URIs (bookmarklets)<br/>
Rob Sanderson: “@vocab”: “javascript:”<br/>
Action #2: Rob Sanderson to create security consideration re javascript URIs and relative IRIs<br/>
Gregg Kellogg: we don’t now check for defined schemes<br/>
Benjamin Young: it’s the responsibility of the document loader to worry about this<br/>
… it could just choose not to resolve troubling URIs<br/>
Ivan Herman: so you put together a URI from the JSON-LD (could happen in many ways).<br/>
… at that level, do we add a security check?<br/>
Benjamin Young: that’s the job of the person using the URI<br/>
Rob Sanderson: Or rather "@vocab": "javascript:document.alert('hi!');"<br/>
Benjamin Young: this isn’t a job for the syntax<br/>
… e.g. data: can hide anything<br/>
… data: URIs<br/>
Gregg Kellogg: this could be used for maliciousness, but it’s on the users of the URIs to be careful<br/>
Rob Sanderson: we don’t do path expansion, we’re doing string concat here. so we won’t catch a lot of stuff<br/>
Benjamin Young: but the advantage of string concat is that it supports non-pathy URIs<br/>
Gregg Kellogg: @vocab is used only for properties<br/>
<b>several:</b> and generally people don’t dereference properties, and nothing in our algorithms says that they should<br/>
Gregg Kellogg: we can modify the API to return only URIs of some form.<br/>
Benjamin Young: we can say “we never use these URIs, so there’s no concern w/i JSON-LD, but if users choose to use them, the usual concerns about URIs from the wild apply”<br/>
Gregg Kellogg: we might consider softening the current restrictions in 3.6.3<br/>
… to use IRI expansion and not string concatenation<br/>
Rob Sanderson: "@vocab": "<a href="http://example.org/ns/"">http://example.org/ns/"</a> and then "@vocab": "/"<br/>
Rob Sanderson: currently you get "<a href="http://example.org/ns//"">http://example.org/ns//"</a> which is unexpected for relative IRIs<br/>
Rob Sanderson: And the expectation would be "<a href="http://example.org/"">http://example.org/"</a><br/>
Ivan Herman: are we making the distinction between the two kinds of resolution disappear?<br/>
Gregg Kellogg: still the issue of concatenation vs. IRI resolution<br/>
Gregg Kellogg: how do I establish @vocab, vs. how do I use it?<br/>
Ivan Herman: if we are in @vocab we do string concat, it’s clean<br/>
… and users just have to know about that<br/>
… let’s don’t mingle concatenation and IRI resolution<br/>
Gregg Kellogg: we’re only interested in resolving `@vocab when it is relative, that’s all<br/>
Ivan Herman: You’re right, but that’s about implementing the system<br/>
… I’m talking about end users<br/>
… if we just have string concat for @vocab, that’s clean, I understand that<br/>
… even if we do IRI resolution instead over here<br/>
… somewhere else. but any problems with doubled slashes, etc., are users problems to deal with<br/>
Rob Sanderson: if we went all the way to have @vocab itself computed and vocab terms resolved via IRI resolution, it breaks things<br/>
… so lets stick cleanly to string concatenation<br/>
Gregg Kellogg: Ok, but these are different use cases.<br/>
Ivan Herman: there is an actual regexp to recognize absolute IRIs, so we can rely on that<br/>
Harold Solbrig: doesn’t the CURI spec speak to this?<br/>
Gregg Kellogg: we don’t use CURIEs, either<br/>
Harold Solbrig: why are we using something else?<br/>
Gregg Kellogg: every RDF serialization uses its own way to discuss short URIs<br/>
… (gkellogg then names more than you would think he could off the top of his head)<br/>
Rob Sanderson: we can’t necessarily construct all legit IRIs, but most of what we can’t is unusual enough not to be problematic<br/>
… if we stick with string concat, we avoid this<br/>
… if you construct stupid @vocabs, that’s your problem<br/>
Proposed resolution: Allow IRIs to be constructed by string concatenation with multiple @vocabs (Rob Sanderson)<br/>
Proposed resolution: Allow IRIs to be constructed by string concatenation with multiple @vocabs, with appropriate security consideration section (Rob Sanderson)<br/>
Adam Soroka: +1<br/>
Gregg Kellogg: +0.9<br/>
Rob Sanderson: +1<br/>
Simon Steyskal: +1<br/>
Adam Soroka: +1<br/>
Harold Solbrig: +1<br/>
Benjamin Young: +1<br/>
Resolution #3: Allow IRIs to be constructed by string concatenation with multiple @vocabs, with appropriate security consideration section<br/>
Ivan Herman: +1<br/>
Benjamin Young: the Chaucer quote fwiw <a href="https://english.stackexchange.com/questions/139073/meaning-of-if-gold-rust-what-shall-the-iron-do">https://english.stackexchange.com/questions/139073/meaning-of-if-gold-rust-what-shall-the-iron-do</a><br/>
</details>

**Comment by iherman** [comment]
> @iherman are the actions we take via Zakim recorded somewhere? I think most of them are disappearing or remain lurking in these call logs on GitHub

I am not sure "lurking" is a good term, but indeed they only appear in the issue comments like https://github.com/w3c/json-ld-syntax/issues/72#issuecomment-433597475.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-01-11-json-ld#section3-2).

- `RESOLVED:  address security concerns related to relative URIs for @vocab in current PRs before closing #72`
<details><summary><i class="differentiate">View the transcript</i></summary>
Allow relative IRIs for @vocab<br/>
Benjamin Young: <a href="https://github.com/w3c/json-ld-syntax/issues/72">https://github.com/w3c/json-ld-syntax/issues/72</a><br/>
syntax - <a href="https://github.com/w3c/json-ld-syntax/pull/114">https://github.com/w3c/json-ld-syntax/pull/114</a><br/>
api - <a href="https://github.com/w3c/json-ld-api/pull/58">https://github.com/w3c/json-ld-api/pull/58</a><br/>
Gregg Kellogg: when we decided to satisfy the need for using the base as the @vocab,<br/>
… I came up with the idea of using an empty string as @vocab.<br/>
… When I implemented it, what I ended up doing was resolve @vocab as a relative URI against the base.<br/>
… So why not allow that in the spec…<br/>
Ivan Herman: ship it! :-)<br/>
Gregg Kellogg: It is uncontroversial, as it does not change past behaviour.<br/>
… Now you can simply use @vocab: “#”, to use relative URIs everywhere.<br/>
Rob Sanderson: –> <a href="https://github.com/w3c/json-ld-syntax/issues/72#issuecomment-433597475">https://github.com/w3c/json-ld-syntax/issues/72#issuecomment-433597475</a><br/>
Rob Sanderson: is this the issue we discussed this during TPAC?<br/>
… if you set vocab to ../# and you had example.org/ns then you get example.org/ns../#<br/>
Gregg Kellogg: I have to improve the text to indicate when standard URI resolution is used, and when string concatenation is used<br/>
Proposed resolution: address security concerns related to relative URIs for @vocab in current PRs before closing #72 (Benjamin Young)<br/>
Ivan Herman: +1<br/>
Benjamin Young: +1<br/>
Ivan Herman: please close issue 72 when you clarify that and merge it.<br/>
Gregg Kellogg: +1<br/>
Rob Sanderson: +1<br/>
Ivan Herman: Let’s reduce the number of open issue<br/>
Pierre-Antoine Champin: +1<br/>
David I. Lehn: +1<br/>
Resolution #4: address security concerns related to relative URIs for @vocab in current PRs before closing #72<br/>
Simon Steyskal: +1<br/>
</details>
