### ISSUE TITLE
Weird wording in spec of Iri Compaction

### ISSUE THREAD

**Issue by pietervdvn** [w3c/json-ld-syntax#75]
The spec of [iri compaction](https://w3c.github.io/json-ld-api/#iri-compaction) states in 2.8

> 2.8.1: If value contains an `@index` member, append the values `@graph@index` and `@graph@index@set` to containers.

> 2.8.4 If value does **not** contain the key `@index`, append the values `@graph@index` and `@graph@index@set` to containers.

In other words, this boils down to _always_ adding `@graph@index` and `@graph@index@set` to the `containers` array.

So either the spec can be simplified or some copy-paste error occurred. Could you please clarify?

**Comment by pietervdvn** [comment]
The same also applies for 2.8.2 and 2.8.5

**Comment by gkellogg** [comment]
Order matters, after running through the steps, `@graph@index` and `@graph@index@set` will be in a different sequence in _containers_. If _value_ contains `@index` we prefer that, otherwise, it’s an acceptable term, but at a lower priority.

**Comment by azaroth42** [comment]
Agree with @gkellogg. Propose close, not an issue :)

**Comment by azaroth42** [comment]
From WG call: @gkellogg to consider whether additional text could be valuable to explain how to read the algorithm steps.

**Comment by gkellogg** [comment]
Consider informative notification for how the container matching works.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-10-12-json-ld#section3-1).

- `RESOLVED:  Mark #75 as editorial, for Gregg to consider whether additional text is needed to explain how to read the algorithm steps`
<details><summary><i class="differentiate">View the transcript</i></summary>
Rob Sanderson: link: <a href="https://github.com/w3c/json-ld-syntax/issues/75">https://github.com/w3c/json-ld-syntax/issues/75</a><br/>
Rob Sanderson: first one seems like a misunderstanding about the algorithm. Greg clarified in the issue. no issue and we can close<br/>
Gregg Kellogg: maybe more descriptive overview could be helpful<br/>
Ivan Herman: the comment came in 8 days ago and the response came in 8 days ago as well. We should probably wait 1 week when we have issue from external members.<br/>
Rob Sanderson: close or make note about editorial changes?<br/>
Adam Soroka: +1 to editorial.<br/>
Gregg Kellogg: make it editorial and look to make sure the description is more robust<br/>
Ivan Herman: marked as editorial and will add reference to the notes<br/>
Rob Sanderson: we can close without further discussion<br/>
Proposed resolution: Mark #75 as editorial, for Gregg to consider whether additional text is needed to explain how to read the algorithm steps (Rob Sanderson)<br/>
Gregg Kellogg: +1<br/>
Rob Sanderson: +1<br/>
Jeff Mixter: +1<br/>
Ivan Herman: +1<br/>
Adam Soroka: +1<br/>
Benjamin Young: +1<br/>
Tim Cole: +1<br/>
Resolution #2: Mark #75 as editorial, for Gregg to consider whether additional text is needed to explain how to read the algorithm steps<br/>
</details>
