### ISSUE TITLE
HTTP parameters for specifying context or frame

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-syntax#8]
When requesting JSON-LD from an HTTP endpoint, it would be useful to provide a reference to a context or frame which should be used by the server to put the results into the proper format.
  * Note that this could be an attack vector on the server, so some provision for white-listing may be in order.

  Original issue is [JSON-LD 1.1 Feature Request : define how to specify the json-ld profile in a request to a server and include framing as an option #491](https://github.com/json-ld/json-ld.org/issues/491)

**Comment by RubenVerborgh** [comment]
We should align this with the work in the W3C DXWG (e.g., https://github.com/w3c/dxwg/issues/261)

**Comment by ajs6f** [comment]
Six kinds of +1. In the field this issue comes up for me at least every three months or so! :grin: The potential for DOS is real, but the need is pressing.

**Comment by azaroth42** [comment]
Propose to discuss this at TPAC in a joint session with DXWG.

**Comment by ajs6f** [comment]
@azaroth42 Is there a DXWG issue to which we can link this?

**Comment by azaroth42** [comment]
https://github.com/w3c/dxwg/issues/261 :)

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-10-26-json-ld#section6).

- `RESOLVED:  Add text to Iana Considerations explicitly allowing the request of a context or frame document, plus security consideration on whitelist, plus tests`
<details><summary><i class="differentiate">View the transcript</i></summary>
Rob Sanderson: we can use space separated lists of URIs, so the profile=”” parameter can contain both the compaction, etc. defined URIs<br/>
… as well as a JSON-LD context or frame URI<br/>
… however, these URIs might collectively get quite long<br/>
Adam Soroka: if you specify a URI don’t you want it to be compacted?<br/>
Rob Sanderson: it could be a frame<br/>
Gregg Kellogg: or a bomb<br/>
Benjamin Young: or a cat photo<br/>
Adam Soroka: do we want to have a default use like it’s assumed it’s a context URI?<br/>
Ivan Herman: what would this look like in practice?<br/>
Rob Sanderson: I’ll write it up…one second…<br/>
Rob Sanderson: ACCEPT: application/ld+json;profile="<a href="http://w3.org/ns/anno.jsonld"">http://w3.org/ns/anno.jsonld"</a><br/>
Rob Sanderson: this would say, “I want this request compacted according to this context”<br/>
Gregg Kellogg: if that JSON-LD URL returns a context<br/>
Benjamin Young: don’t dereferences things found in profile params<br/>
… because proxies<br/>
Gregg Kellogg: right, security concerns/needs should be expressed<br/>
Benjamin Young: we used the entire string as the “media type” for Web Annotation<br/>
… with no expressed intent or idea of dereferencing that context URI<br/>
Adam Soroka: I’m not too worried about big headers<br/>
… if you’re going to be this particular about it, then that’s a “cost” you’ll face<br/>
Rob Sanderson: and the multiple URIs in profile=”” is not a problem?<br/>
Adam Soroka: no, I think that’s fine<br/>
Rob Sanderson: if you don’t care if you’re flattened or compacted, then don’t state it and use the context for whichever you’re returning<br/>
Benjamin Young: is there priority among these strings?<br/>
… or do they just work as flags?<br/>
Rob Sanderson: they’re just flags<br/>
Adam Soroka: do we want q=”” parameters for this?<br/>
Rob Sanderson: I’d say it’s an error condition to have multiple contexts given<br/>
Benjamin Young: is the intent to continue–as Web Annotation did–as a single opaque string?<br/>
… or are we switching on each piece?<br/>
… mostly it’s a question for me about upgrading existing Web Annotation servers (and the like)<br/>
… so are they opaque “whole” strings? or are we taking them apart in some way?<br/>
Rob Sanderson: so, in the case of compaction at least, we could have a default that maps to compaction<br/>
… which is how profile=”” is used in the cases that we know<br/>
Gregg Kellogg: are you going to help write these tests?<br/>
Rob Sanderson: sure. I’ll help write those tests<br/>
… and the paragraph/dependencies<br/>
Gregg Kellogg: and at the moment we don’t have complete HTTP header tests…but need those<br/>
Rob Sanderson: I know someone (bigbluehat) who’s done this already<br/>
Benjamin Young: we’re continuing the Web Annotation validation/testing tooling work at <a href="http://annotator.apache.org/">http://annotator.apache.org/</a><br/>
Gregg Kellogg: so, there are a few HTTP tests now<br/>
… they were originally in an .htaccess file<br/>
… but right now it’s left up to the implementations to act as if the headers were expressed in the responses or not<br/>
… the test suite should ideally run off a W3C mirror that implement these .htaccess<br/>
Benjamin Young: curious which bits you needed in .htaccess<br/>
Gregg Kellogg: there’s a remote access manifest in the API<br/>
Gregg Kellogg: <a href="https://github.com/w3c/json-ld-api/blob/master/tests/remote-doc-manifest.jsonld">https://github.com/w3c/json-ld-api/blob/master/tests/remote-doc-manifest.jsonld</a><br/>
Gregg Kellogg: for example <a href="https://github.com/w3c/json-ld-api/blob/master/tests/remote-doc-manifest.jsonld#L34">https://github.com/w3c/json-ld-api/blob/master/tests/remote-doc-manifest.jsonld#L34</a><br/>
… this one tests a application/jldTest content type<br/>
… which in this case should fail<br/>
… others here deal with redirects<br/>
… also, another for the Link header <a href="https://github.com/w3c/json-ld-api/blob/master/tests/remote-doc-manifest.jsonld#L84">https://github.com/w3c/json-ld-api/blob/master/tests/remote-doc-manifest.jsonld#L84</a><br/>
… for all of these we’re analyzing the JSON-LD result<br/>
… so we probably want similar ones analyzing the HTTP headers themselves<br/>
Proposed resolution: Add text to Iana Considerations explicitly allowing the request of a context or frame document, plus security consideration on whitelist, plus tests (Rob Sanderson)<br/>
Rob Sanderson: +1<br/>
Gregg Kellogg: +1<br/>
Adam Soroka: +1<br/>
Benjamin Young: +1<br/>
Ivan Herman: +1<br/>
Resolution #5: Add text to Iana Considerations explicitly allowing the request of a context or frame document, plus security consideration on whitelist, plus tests<br/>
</details>

**Comment by gkellogg** [comment]
Something to resolve:

If the ACCEPT header includes a json-ld media type with a context or frame profile that the server won't support (e.g., black/white list) I presume it would skip that request and go to the next highest-priority media type it supports (possibly application/ld+json without a profile or without a specific context/frame) returning [status 415](https://httpstatuses.com/415) if none found.

This could mean not returning any JSON-LD if profile cannot be satisfied.

Alternatively, the server should satisfy the request as best it can without consideration of the profile parameter.

**Comment by Conal-Tuohy** [comment]
I think it's correct that the server is supposed to consider the entire value of the `Accept` header, including any media type parameters  (profiles, etc) in deciding which is the best representation of the resource. RFC7231 gives an analogous example of selecting among various kinds of plain text:

https://tools.ietf.org/html/rfc7231#page-39

I think it would be good practice for clients to specify both a profile and also "unprofiled" JSON-LD (if they can actually accept that), e.g. `application/ld+json, application/ld+json;profile=foo`. It' should not be necessary for a client to specify a lower `q` value for generic `application/ld+json` than for `application/ld+json;profile=foo`, because the server ought to prefer the "more specific" value anyway.

If a client sends `Accept: application/ld+json;profile=foo` without also `application/ld+json`, the server could either return a 406, or could return a 200 with its own "best guess" content type (as it would be entitled to do if the client had not sent an `Accept` header at all). In such a case, it would make sense, to me, to return JSON-LD rather than some other RDF media type.

**Comment by ajs6f** [comment]
Wow, I got that completely backwards! Thanks for the correction, @Conal-Tuohy. 

Given that many clients will be expecting to use compacted JSON-LD as JSON, I think a 4xx is by far the best answer here. Non-compacted forms are going to be more surprising and troublesome than helpful to such clients.

**Comment by gkellogg** [comment]
Better than status 415 is [status 406 "Not Acceptable"](https://httpstatuses.com/406):

> The target resource does not have a current representation that would be acceptable to the user agent, according to the proactive negotiation header fields received in the request, and the server is unwilling to supply a default representation.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-01-04-json-ld#section4-1).

- `RESOLVED:  limit profile parameter use to URI’s, but continue to pursue an alternative to the profile media type parameter for client-signaled frames and contexts URLs for servers to (potentially) use when providing responses`
<details><summary><i class="differentiate">View the transcript</i></summary>
4.1. HTTP parameters for specifying context or frame<br/>
Benjamin Young: <a href="https://github.com/w3c/json-ld-syntax/issues/8">https://github.com/w3c/json-ld-syntax/issues/8</a><br/>
Benjamin Young: * syntax - <a href="https://github.com/w3c/json-ld-syntax/pull/111">https://github.com/w3c/json-ld-syntax/pull/111</a><br/>
Benjamin Young: * framing - <a href="https://github.com/w3c/json-ld-framing/pull/34">https://github.com/w3c/json-ld-framing/pull/34</a><br/>
Benjamin Young: * api - <a href="https://github.com/w3c/json-ld-api/pull/56">https://github.com/w3c/json-ld-api/pull/56</a> (work in progress)<br/>
Benjamin Young: gkellogg has the lion’s share of the work done on this<br/>
Gregg Kellogg: the first PR (syntax doc, #111) pretty much ready to go<br/>
… removed language about quotes for the value of profile params<br/>
… which is not true in general<br/>
… only if multiple URIs are used, and added some examples with different types of profile params<br/>
Ivan Herman: I had a comment on that<br/>
… content, not editorial<br/>
… a sentence says that JSON-LD processors may restrict URIs for context and frames<br/>
… which I read as saying, “If I’m a JSON-LD processor, I can refuse any context except this particular one”<br/>
… is that really what we mean<br/>
Gregg Kellogg: well, this could become an attack vector, so we allow servers to restrict the action<br/>
Gregg Kellogg: framing is potentially expensive computationally<br/>
… and people have demonstrated attacks via context<br/>
… which we think we’ve mostly fixed, but obviously we can’t rule it entirely out<br/>
… going back to the CG, there was this desire to restrict present there<br/>
Ivan Herman: i have two problems…<br/>
… this is clearly non-editorial<br/>
… have we discussed/voted on this restriction?<br/>
… shouldn’t be in an editorial PR.<br/>
… I don’t understand the problem this solves<br/>
Gregg Kellogg: this is part of the request header.<br/>
Ivan Herman: oh, the request header? (not the response)<br/>
Gregg Kellogg: this signals the server as to what the client wants<br/>
… the server must examine the profile param and if it isn’t acceptable, return a 406<br/>
… this new language just gives license to the server to do just that if the context is unacceptable<br/>
… you could also fall-back in various ways<br/>
Ivan Herman: Okay, I misunderstood what was done, so that’s okay<br/>
… but still, this is more than editorial<br/>
Gregg Kellogg: I don’t say that this is editorial<br/>
… I folded in the previous discussions on this<br/>
Ivan Herman: sorry for the interrupt, fine with this. I will put in a link to this discussion into the PR<br/>
… must be documented, now it is<br/>
… we just want to document that everyone is fine with this<br/>
Benjamin Young: I’ve got a nit<br/>
… about the quotes being optional save for multiple URIs<br/>
Gregg Kellogg: for spaces<br/>
… and I show examples of this<br/>
… we don’t mandate that single spaces must be used<br/>
… it’s just whitespace as defined by the rFC<br/>
Benjamin Young: okay, thanks<br/>
Gregg Kellogg: we have also the PR for the API doc<br/>
Gregg Kellogg: <a href="https://github.com/w3c/json-ld-api/pull/56">https://github.com/w3c/json-ld-api/pull/56</a><br/>
Gregg Kellogg: there is w-i-p on the API at that PR<br/>
… framing was a more minor change<br/>
Gregg Kellogg: <a href="https://github.com/w3c/json-ld-framing/pull/34">https://github.com/w3c/json-ld-framing/pull/34</a><br/>
Gregg Kellogg: the controversial point bigbluehat raised is whether adding a framing URI changes the semantics enough to make it inappropriate<br/>
… as a profile param<br/>
… online discussion indicates not<br/>
… the change requires the profile param<br/>
… which changes current behavior for people requesting frames<br/>
… there might b more changes requireed for this for optinality<br/>
Gregg Kellogg: the idea was that a frame would be represented by a mimetype<br/>
… but no one implemented that<br/>
… and now we’ve moved to using a profile param for frame<br/>
… so the question is, must the profile param appear, or is it optional/advisory<br/>
… this param is for getting a doc that is a frame<br/>
… and would appear on the response as well<br/>
Benjamin Young: yes, we would want that on the response as well<br/>
Benjamin Young: <a href="https://tools.ietf.org/html/rfc6906">https://tools.ietf.org/html/rfc6906</a><br/>
Gregg Kellogg: we need more discussion on that PR<br/>
Adam Soroka: <a href="https://github.com/w3c/json-ld-framing/pull/34">https://github.com/w3c/json-ld-framing/pull/34</a><br/>
Gregg Kellogg: the API PR (<a href="https://github.com/w3c/json-ld-api/pull/56)">https://github.com/w3c/json-ld-api/pull/56)</a> is just tests for this new behavior<br/>
… I couldn’t see what language to add to the API, otherwise<br/>
… the API do is concerned with what happens once you’ve requested a doc and are processing the result<br/>
… we don’t need to specify how to use an Accept header<br/>
Benjamin Young: this would only be for requesting a single doc in various representation<br/>
… I’m glad that framed docs aren’t new mediatypes<br/>
… but it seems unlikely that one document would be all the things at once (frame, context, instance)<br/>
Gregg Kellogg: but you aren’t requesting a doc, you are requesting a resource.<br/>
… e.g. for SPARQL users<br/>
Gregg Kellogg: profile contains one or more of our URIs, as well as URLs to contexts, frames, etc.<br/>
David Newbury: a real-world example: we have resources we’d like to be able to provide either as schema.org or CIDOC-CRM<br/>
… same data, difference context/framing<br/>
Gregg Kellogg: only the non-registered URLS would be treated as dereferencable<br/>
… similar to when the mimetype is just application/json and you stick the contet in a header<br/>
Benjamin Young: this is where I get concerned about violating the RFC– the profile param shouldn’t be dereferenced<br/>
Gregg Kellogg: good point…<br/>
… my impression was that we could define this behavior, but we do need to review<br/>
Benjamin Young: in the Web Annotation we avoided triggering new representations via the profile param, only selecting from extant representations<br/>
Ivan Herman: <a href="https://tools.ietf.org/html/rfc6906">https://tools.ietf.org/html/rfc6906</a><br/>
Benjamin Young: this is a supernice feature, but is this where it belongs?<br/>
Ivan Herman: what the RFC (<a href="https://tools.ietf.org/html/rfc6906#section-3)">https://tools.ietf.org/html/rfc6906#section-3)</a> does say is:<br/>
“A profile MUST NOT change the semantics of the resource representation when processed without profile knowledge, so that clients both with and without knowledge of a profiled resource can safely use the same representation.”<br/>
Benjamin Young: There is also <a href="https://tools.ietf.org/html/rfc4288#section-4.3">https://tools.ietf.org/html/rfc4288#section-4.3</a><br/>
Ivan Herman: so this may indeed be a problem<br/>
Gregg Kellogg: the use of a context does not change the semantics of a representation, just the syntax<br/>
Benjamin Young: it’s the functionality concern<br/>
… if these are URLs (not merely URIs) they will be looked up and used for computation<br/>
Ivan Herman: it is an identifier; to quote further from <a href="https://tools.ietf.org/html/rfc6906#section-3:">https://tools.ietf.org/html/rfc6906#section-3:</a><br/>
“Profiles are identified by URI. However, as is the case with, for example, XML namespace URIs, the URI in this case only serves as an identifier,”<br/>
Ivan Herman: it is at the beginning of that section<br/>
Gregg Kellogg: rfc4288#section-4.3 is a different case of profile: that’s the header vs the mimetype<br/>
Gregg Kellogg: e.g. dc:name vs schema:name<br/>
… totally different graphs<br/>
… but for framing, it’s the same graph<br/>
… and client can reframe or re-compact or whatever<br/>
… for bigbluehat’s case, where there’s a range of possible contexts…<br/>
… two ways to interpret that: first, I want the Schema context vs the DC context<br/>
… or, I want “name” vs “schema:name” where the terms used are different<br/>
Benjamin Young: in the case of conneg, you could list several contexts<br/>
… and the sever will compute on your request and select something<br/>
… that’s not a processing instruction<br/>
… that’s a great idea, but it should go in a different box<br/>
Pierre-Antoine Champin: not fully agree with gkellogg about changing strings in the JSON for different contexts<br/>
… in both cases, the semantics are the same<br/>
… the condition for selecting different vocabularies is that the semantics of the vocabularies is the same<br/>
… in both cases, the changes are at the syntax level, just at concrete or abstract syntax<br/>
Gregg Kellogg: if we look at the test suite, what might be considered?<br/>
… one, you can take the result, expand it, and compare<br/>
… or two, turn them into RDF and compare the graphs for isomorphism<br/>
… (or in framing, a strict subgraph relationship)<br/>
Ivan Herman: +1 to gregg<br/>
David Newbury: I’m assuming that I have all the data and am just selecting from it, not doing new processing<br/>
Ivan Herman: whither shall we wander?<br/>
… what do we do if profiles are not the correct choice?<br/>
… our own request header?<br/>
… is there an extant header we can adopt?<br/>
Benjamin Young: Profile seems like the wrong vehicle for this signaling, but we cannot discard the use case<br/>
Proposed resolution: limit profile parameter use to URI’s, but continue to pursue an alternative to the profile media type parameter for client-signaled frames and contexts URLs for servers to (potentially) use when providing responses (Benjamin Young)<br/>
Gregg Kellogg: <a href="https://www.w3.org/TR/json-ld11/#interpreting-json-as-json-ld">https://www.w3.org/TR/json-ld11/#interpreting-json-as-json-ld</a><br/>
Gregg Kellogg: we might borrow from the way we handle application/json<br/>
… in a response header, we add a link header targeting the context<br/>
… we could use a Link header on the request<br/>
Ivan Herman: we would need a more detailed description<br/>
Benjamin Young: <a href="https://tools.ietf.org/html/rfc8288">https://tools.ietf.org/html/rfc8288</a><br/>
Benjamin Young: you sure can use a Link header on the request<br/>
… but let’s get to a proposal<br/>
… we need to get URLs out of the profiles<br/>
… and there is clear desire in the group for this functionality<br/>
… link rel= might be a nice way to do that<br/>
Proposed resolution: limit profile parameter use to URI’s, but continue to pursue an alternative to the profile media type parameter for client-signaled frames and contexts URLs for servers to (potentially) use when providing responses (Benjamin Young)<br/>
Gregg Kellogg: +1<br/>
Benjamin Young: +1<br/>
Adam Soroka: +1<br/>
Jeff Mixter: +1<br/>
Harold Solbrig: +1<br/>
Tim Cole: +1<br/>
Ivan Herman: do we suspend all three PRs?<br/>
Gregg Kellogg: not necessarily framing, but that needs its own discussion<br/>
David Newbury: +1<br/>
Pierre-Antoine Champin: +1<br/>
Ivan Herman: +1<br/>
Gregg Kellogg: if there is no actual language in the API doc, the tests that have been added there might belong in the syntax doc<br/>
Resolution #2: limit profile parameter use to URI’s, but continue to pursue an alternative to the profile media type parameter for client-signaled frames and contexts URLs for servers to (potentially) use when providing responses<br/>
Benjamin Young: let’s leave it to gkellogg as to how he’d like to manage the PRs, whether to add more commits or start afresh or whatever<br/>
</details>

**Comment by azaroth42** [comment]
I don't understand the resolution. The profile parameter can ONLY use:

> A non-empty list of space-separated URIs 

According to the IANA registration of `application/ld+json`

**Comment by BigBlueHat** [comment]
> I don't understand the resolution. The profile parameter can ONLY use:
> 
> > A non-empty list of space-separated URIs
> 
> According to the IANA registration of `application/ld+json`

Exactly. 😃 The original proposal was to use them as UR**L**'s--extracting them from the profile value and dereferencing them and using them when parsing the data document.

It was determined that client's requesting processing constraint documents (i.e. frames, contexts) was a potentially viable feature request, but that the `profile` media parameter was the wrong vehicle for that.

@gkellogg mentioned using `Link` instead and has added that approach to the *work-in-progress* PR https://github.com/w3c/json-ld-api/pull/56

There will certainly need to be discussion about the use of `Link` (per-process), but overall it feels more correct than using `profile`.

I'd propose we change the title of this issue (s/parameters/header) to match reality. That sound OK?

**Comment by azaroth42** [comment]
I'm :-1: on the resolution as I understand it. It conflates descriptive metadata and protocol transactions unnecessarily by applying rules intended for responses to the functionality of requests.

Each entry in the Accept header is treated individually. It is perfectly reasonable to ask for json-ld or rdf/xml (syntax change) ; for json-ld or plain text (semantics are lost) ; or for two different flavors of json-ld. 

I'm also :-1: on changing parameter to header. Link headers are not a functional way to request content negotiable resources, as they lack all of the prioritization of q values.

**Comment by BigBlueHat** [comment]
@azaroth42 this has moved beyond content negotiation--which is I think where things are getting tangled and why it probably needs it's own issue(s).

First, using `profile` with the media type parameter is still (and will remain!) a viable way to content negotiate for a resource:
```http
Accept: application/ld+json;profile="http://www.w3.org/ns/anno.jsonld"
```
and
```http
Accept: application/ld+json, application/ld+json;profile="http://www.w3.org/ns/anno.jsonld"
```
still request that the server send back something that matches one of those (possibly profiled) types.

However, this feature request included *dereferencing* the requested profile URL and *processing* that to generate the content--which per a stack of RFCs--goes against the intended use of the `profile` parameter as simply bearing identifiers and leaving it up to the server to determine the proper response for the request (i.e. `profile` should not be used to create a processing instruction).

Consequently, `Link` (which is a viable header on both requests and responses) was proposed by @gkellogg as we were wrapping up the call with the promise of future exploration and follow-on discussion about that particular approach (and the feature in general).

There was not (and is not to my knowledge) any intention to replace or remove the use of `profile`, just to make sure it's not misused as a processing instruction.

Any clearer? 😄

**Comment by gkellogg** [comment]
@BigBlueHat is correct, the `profile` parameter remains, and is used with a registered URI. We define four such URIs, and certainly other specs can define their own profiles and register them.

After closer inspection of the RFCs it seemed that our use of the `profile` parameter to _also_ reference the context or frame to use was outside of the usage pattern proscribed for such parameters. Since we already have the Link header, used for responses, using it for requests is reasonable.

However, your point about not being able to use a specific context URL as part of content negotiation is well taken, although it's not clear how a server would distinguish between different context or frame URLs to make a decision, without first dereferencing them, or using an internal registry.

I'm not sure how we could allow for content negotiation on a context URL given the RFCs available to us.

**Comment by azaroth42** [comment]
> However, this feature request included dereferencing the requested profile URL and processing that to generate the content

I don't see that anywhere in this issue, nor the referenced original issue. Can you provide a link?

**Comment by BigBlueHat** [comment]
> I don't see that anywhere in this issue, nor the referenced original issue. Can you provide a link?

Hrm. It may have first come up at our TPAC conversations minuted above: https://github.com/w3c/json-ld-syntax/issues/8#issuecomment-433597582

Which is why this is marked as having security concerns. There's no security concern if these are just opaque identifiers.

**Comment by azaroth42** [comment]
It came up as a concern, certainly. Don't do that then, if there is a concern :) Just use a whitelisted set of profiles. IOW, there is no issue here about URI vs URL that isn't already addressed by an expanded security considerations section.

**Comment by gkellogg** [comment]
From [RFC 6906 3.0](https://tools.ietf.org/html/rfc6906#page-3)

> Profiles are identified by URI.  However, as is the case with, for
   example, XML namespace URIs, the URI in this case **only serves as an
   identifier, meaning that the presence of a specific URI has to be
   sufficient for a client to assert that a resource representation
   conforms to a profile**.

This implies that an opaque URL is not appropriate for use in the profile, as, unless specifically registered, it cannot be dereferenced to affect the representation of the resource; at least, that was my take away from our discussion. This implies that our resolution, which @BigBlueHat mentioned from TPAC violates the stated purpose of the profile parameter.

**Comment by azaroth42** [comment]
The next sentence, however clarifies that:

> profiles MAY be defined in a way
>  that the URIs do identify retrievable profile description and thus
>  can be accessed by clients by dereferencing the profile URI

So I continue to disagree that there's anything wrong with our usage.

**Comment by BigBlueHat** [comment]
> For profiles intended for use in environments where clients may encounter
   unknown profile URIs, profile maintainers SHOULD consider to make the
   profile URI dereferencable and provide useful documentation at that
   URI.

@azaroth42 from what I can tell from the rest of the surrounding examples (mostly about podcasts), the intent is that at most a "dereferencable URI" (aka a URL) value for `profile` is meant to return *documentation* (for machines or humans). Most of the examples point to using human-friendly HTML documentation URLs as the identifier (however derefencable) of the "profile" of the format.

The use case of *applying* a profile seems a bit different than asking if the server has a resource *conforming* to a profile--hence the processing instruction comments from earlier.

**Comment by BigBlueHat** [comment]
As an example, if I send `Accept: application/ld+json;profile="http://www.w3.org/ns/anno.jsonld"` to a server, I would *not* expect the server to take whatever JSON(-LD) it had for the resource and attempt to apply that context URL to it.

However, it *would* be my expectation that the response would [406](https://http.cat/406) if the only thing on disc were JSON(-LD) which did *not* conform to that profile (since I only asked for the profiled variant).

The distinction seems important from a server implementation perspective, and having a means to intentionally request or initiate such processing *does* seem useful...but seems best signaled by something less implicitly inert.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-01-11-json-ld#section3-1).

- `RESOLVED:  remove normative discussion of use of Link header usage for response augmentation–move to best practice for now`
<details><summary><i class="differentiate">View the transcript</i></summary>
HTTP parameters for specifying context or frame (round 2!)<br/>
Benjamin Young: <a href="https://github.com/w3c/json-ld-syntax/issues/8">https://github.com/w3c/json-ld-syntax/issues/8</a><br/>
syntax - <a href="https://github.com/w3c/json-ld-syntax/pull/111">https://github.com/w3c/json-ld-syntax/pull/111</a> (open)<br/>
framing - <a href="https://github.com/w3c/json-ld-framing/pull/34">https://github.com/w3c/json-ld-framing/pull/34</a> (merged)<br/>
api - <a href="https://github.com/w3c/json-ld-api/pull/56">https://github.com/w3c/json-ld-api/pull/56</a> (ready for review)<br/>
Benjamin Young: the framing PR is already merged — mostly clerical, regarding IANA registration.<br/>
Gregg Kellogg: the PR is about the possibility for a client to specify the contex with which it wishes the retrieved data to be processed.<br/>
… Last week, we discussed this, and realized that dereferencing the value of the profile attribute is something that we don’t want to do.<br/>
… I had to rewrite this part. This information is now to be conveyed with a Link header.<br/>
… A consequence is that the context URL can no more be used for content negotiation.<br/>
Rob Sanderson: my understanding about the move away from the profile parameter is about the dereferencability?<br/>
Gregg Kellogg: not exactly. The RFC indicates that the URI used as profile parameter can be dereferencable, for documentation.<br/>
… But the execution should not be determined by derefencing it.<br/>
Rob Sanderson: Why not simply specify that, if a server receives a profile URI that it does not know,<br/>
… it just answers with 406?<br/>
… We should not specify how the server does the serialization.<br/>
… That’s implementation detail, not specification.<br/>
… Given that, I don’t think there is any expectation that the server should dereference;<br/>
… but it may do that if it thinks that’s a good thing.<br/>
Benjamin Young: the spec last week was explicitly specifying that the profile parameter should be dereferenced.<br/>
… Going away from this lead us away from the profile parameter all together.<br/>
… But I see where you are going.<br/>
Gregg Kellogg: We should have both mechanisms: one to query a well known profile,<br/>
… and one to provide a previously unknown context, to be processed by the server.<br/>
Rob Sanderson: we can’t prevent the profile from the accept header; it is part of the media-type.<br/>
… We should embrace what people are going to do anyway,<br/>
… which is a profile parameter in the accept header.<br/>
Benjamin Young: I’m concerned we are defining a server API for JSON-LD, which is not what we are meant to do.<br/>
Rob Sanderson: +1 to bigbluehat to steer away from JSON-LD-REST<br/>
Rob Sanderson: (not because it’s a bad thing, but because we’re not chartered to do that!)<br/>
Benjamin Young: We should provide a list of profile URI that we recommend.<br/>
… Whatever else people use as profile URIs is their business.<br/>
… The Links header is more an API spec, which would be LDP2’s job, not ours…<br/>
Gregg Kellogg: there was always a problem for the profile parameter for, e.g., compacted<br/>
… there was no way to convey the context against which compaction was done [not sure I got it right]<br/>
… This has been long discussed in the CG.<br/>
… The Link header was a way to address that.<br/>
Benjamin Young: Is this purely an IANA registration and suggesting good practices?<br/>
… I fear that too much HTTP matter in the spec and/or the test,<br/>
… will feel like a MUST or a SHOULD for any JSON-LD implementation.<br/>
Gregg Kellogg: that’s a way to ensure that people using it know how to use it.<br/>
… The bit about the Link header could go in a different (REST?) spec or a best practices doc.<br/>
Rob Sanderson: +1 to best practices tests<br/>
Gregg Kellogg: We should remove any normative discussion about the Link header,<br/>
… and replace it with a more vague mention to “header fields, to be described elsewhere”.<br/>
… And move the current test elsewhere, probably a new spec.<br/>
Proposed resolution: remove normative discussion of use of Link header usage for response augmentation–move to best practice for now (Benjamin Young)<br/>
Ivan Herman: +1<br/>
Rob Sanderson: +1<br/>
Gregg Kellogg: +1<br/>
Benjamin Young: +1<br/>
Simon Steyskal: +1<br/>
Pierre-Antoine Champin: +1<br/>
Resolution #3: remove normative discussion of use of Link header usage for response augmentation–move to best practice for now<br/>
Gregg Kellogg: Do we want to create new spec for server behaviour, or a best practices document?<br/>
… And then should we create a different repository?<br/>
Ivan Herman: I prefer many small repos, but I know not everyone agrees.<br/>
… Wherever the editors feel it more conformable.<br/>
… Should we close the issue?<br/>
Gregg Kellogg: I still have a few changes to make.<br/>
… After a small period for people to concur,<br/>
… I’ll merge the changes.<br/>
Ivan Herman: and then close the issue at the same time.<br/>
</details>

**Comment by ajs6f** [comment]
I'm coming in _very_ late on this, but wrt a `Link` header, could we rely on previous work [here](https://tools.ietf.org/html/rfc6906)? I understand there could be some issues with q-value ordering (or rather, the lack thereof).
