### ISSUE TITLE
Can SRI be used in JSON-LD and for which use cases?

### ISSUE THREAD

**Issue by ajs6f** [w3c/json-ld-syntax#86]
[Subresource Integrity](https://www.w3.org/TR/SRI) can be used in HTML to provide integrity support for portions of HTML documents. It may be possible to reuse that pattern in JSON-LD, and it might support various use cases around integrity, but the basic question of whether it can be done in JSON-LD syntax is still open.

**Comment by davidlehn** [comment]
See also: https://github.com/w3c/json-ld-syntax/issues/9

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-12-14-json-ld#section5-1).

- `RESOLVED:  azaroth to open an issue about annotating context URLs potentially with validity/integrity, etc. metadata`
<details><summary><i class="differentiate">View the transcript</i></summary>
Can SRI be used in JSON-LD for which use cases?<br/>
Benjamin Young: <a href="https://github.com/w3c/json-ld-syntax/issues/86">https://github.com/w3c/json-ld-syntax/issues/86</a><br/>
Benjamin Young: <a href="https://w3c.github.io/webappsec-subresource-integrity/">https://w3c.github.io/webappsec-subresource-integrity/</a><br/>
Benjamin Young: if anyone understands this first issue, we can discuss it<br/>
Benjamin Young: … SRI = Sub-Resource Integrity<br/>
Benjamin Young: SRI is something HTML implementors use to state the integrity of things<br/>
… I believe adam wanted to introduce something like SRI for e.g., validating contexts<br/>
Gregg Kellogg: it’s an intriguing idea, esp. in the context of referencing external contexts<br/>
… it does come with a cost though..<br/>
… I think the motivation behind this was to provide means for side-loading stuff<br/>
Benjamin Young: <a href="https://w3c.github.io/webappsec-subresource-integrity/#integrity-metadata">https://w3c.github.io/webappsec-subresource-integrity/#integrity-metadata</a><br/>
Rob Sanderson: is it about whether we can use the abstract definition of integrity stuff SRI defines<br/>
Ivan Herman: there have been 2 diff. issues that came up during TPAC<br/>
… one of them was about using a local version of the context<br/>
… all go in the direction of annotating a link<br/>
… maybe we should postpone this specific issue until we investigated the general picture more thoroughly<br/>
Benjamin Young: yeah, people want to be able to state “more” things about a context than they currently can<br/>
Benjamin Young: related to <a href="https://github.com/w3c/json-ld-syntax/issues/9">https://github.com/w3c/json-ld-syntax/issues/9</a><br/>
Benjamin Young: i.e., that it is sealed<br/>
… I don’t think we have any specific actions to take<br/>
Rob Sanderson: I think there’s some meta discussion going on<br/>
Proposed resolution: someone should open an issue about annotating context URLs potentially with validity/integrity, etc. metadata (Benjamin Young)<br/>
Rob Sanderson: we may need to introduce new keywords that identify “new metadata” about a context<br/>
… distinction between inline context and reference to metadata of external context<br/>
Proposed resolution: azaroth to open an issue about annotating context URLs potentially with validity/integrity, etc. metadata (Benjamin Young)<br/>
David I. Lehn: if such metadata feature exists, people may see that as a way to add comments and docs and such as in previous closed issues<br/>
Rob Sanderson: +1<br/>
Benjamin Young: +1<br/>
Rob Sanderson: we should not have the same discussion again in January<br/>
Gregg Kellogg: +1<br/>
Tim Cole: +1<br/>
Simon Steyskal: +1<br/>
Pierre-Antoine Champin: +1<br/>
David I. Lehn: +1<br/>
Ivan Herman: +1<br/>
Jeff Mixter: +1<br/>
Resolution #3: azaroth to open an issue about annotating context URLs potentially with validity/integrity, etc. metadata<br/>
</details>

**Comment by BigBlueHat** [comment]
Also relates to discussions of #9 content addressable contexts as those would come with some amount of implicit integrity checks.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-04-26-json-ld.html#section3-4).

- `RESOLVED:  Close syntax #86, as being dependent on deferred #108, and duplicates only use case for it`
<details><summary><i class="differentiate">View the transcript</i></summary>
Can SRI be used in JSON-LD and for which use cases?<br/>
Ivan Herman: <a href="https://github.com/w3c/json-ld-syntax/issues/86">https://github.com/w3c/json-ld-syntax/issues/86</a><br/>
Rob Sanderson: answer is no<br/>
Ivan Herman: I propose this issue can simply be closed by referring to the previous issue<br/>
Proposed resolution: Close syntax #86, as being dependent on deferred #108, and duplicates only use case for it (Rob Sanderson)<br/>
Gregg Kellogg: +1<br/>
Benjamin Young: +1<br/>
Rob Sanderson: +1<br/>
Ruben Taelman: +1<br/>
Simon Steyskal: +1<br/>
Tim Cole: +1<br/>
Pierre-Antoine Champin: +1<br/>
Dave Longley: +1<br/>
David Newbury: +1<br/>
Ivan Herman: +1<br/>
David I. Lehn: +1<br/>
Resolution #5: Close syntax #86, as being dependent on deferred #108, and duplicates only use case for it<br/>
</details>

**Comment by iherman** [comment]
Ref #108
