### ISSUE TITLE
Content addressable contexts

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-syntax#9]
Provide a means for refering to a remote context without without requiring it to be downloaded
* HTML scribe integrity?
* IPFS
* `duri` or `tdb` schemes
* “frozen” contexts

Original issue [Content addressable contexts #547](https://github.com/json-ld/json-ld.org/issues/547)

**Comment by azaroth42** [comment]
I think the question to be answered for this issue is what features are needed, and what affordances in the *syntax* are then required to make those features possible.  All of the suggested patterns in the original issue work out of the box, as the context IRI is not required to be HTTP/S. 

> If the node object contains the @context key, its value must be null, an absolute IRI, a relative IRI, a context definition, or an array composed of any of these.

Sub-resource integrity is an interesting proposition, as would metadata for the context to declare it "frozen", which seems related to #20.

**Comment by cwebber** [comment]
From the previous bug, I [mentioned magnet URIs](https://github.com/json-ld/json-ld.org/issues/547#issuecomment-352326610) and @gkellogg said:

> Cool, I was unaware of these. Of course, it's a "de facto" standard, so not really referencable.

Honestly I think magnet URIs do half of what we want in a general and widely used way and can be used with a variety of p2p networks.  Maybe it's time to actually standardize them?

**Comment by iherman** [comment]
I wonder whether this is for us to deal with. If the value of `@id` is a URI but not _necessarily_ an HTTP URI, then JSON-LD can use any scheme that the community defines out there, we should not be the ones defining it.

The only one so far that seems to be different is the separate `@integrity` approach which would need some extra terms. I wonder, however, if we should not make it somehow more general, by allowing for something like `@fetch-attributes` (probably not the right term) that would allow the addition of extra attributes that are related to the fetch of the content. Ie, one could have something like 

```json
"@context" : {
    "@id" : "https://...",
   "@fetch-attribute" : {
        "integrity" : ""sha384-Li9vy3...",
       "crossorigin": "anonymous",
      "....."
   }
}
```

My worry is to cast in concrete keywords reflecting the state of today and not be future proof enough in an area that is fast evolving.

(Caveat: I am not an expert in all these various fetch attributes...)

**Comment by cwebber** [comment]
so a) I don't think this is really something that needs to be standardized *in the json-ld spec*
but b) I think it's an issue of best practice for json-ld implementations so it's worth discussing it here.

**Comment by iherman** [comment]
@cwebber 

> I don't think this is really something that needs to be standardized _in the json-ld spec_

Fully agree. But should be sure that existing standards can be used within JSON-LD. In this sense, it _may_ be more than just best practice (see again the way integrity could be handled).

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-10-25-json-ld#section3-2).

- `ACTION:  Rob Sanderson to create issues for ContextList and DocumentLoader editorial changes`
<details><summary><i class="differentiate">View the transcript</i></summary>
Rob Sanderson: the issue from my POV is that it would be nice to have a feature that let’s context be “sealed” or “frozen”<br/>
… this lets people identify an immutable context<br/>
… this could prevent a huge amount of people retrieving context over the wire<br/>
Dan Brickley: cf <a href="https://www.w3.org/RDF/Group/Schema/openissues.html#c12">https://www.w3.org/RDF/Group/Schema/openissues.html#c12</a> “Closed 19980707 - deferred until 1.1; M+S to supply a mandatory extensions mechanism” (“We would like to define a mechanism for ‘sealing’ an RDF Class, so that it becomes illegal to make certain RDF statements involving it. This is loosly analagous to the notion of ‘final’ classes in Java / OO programming. …”)<br/>
Rob Sanderson: as well as preventing people from overriding term expansion<br/>
… since choosing an expansion is “last in wins”<br/>
Ivan Herman and Gregg Kellogg: Those are two different issues!<br/>
Rob Sanderson: <a href="https://github.com/w3c/json-ld-syntax/issues/9">https://github.com/w3c/json-ld-syntax/issues/9</a> is the first part of what I was describing<br/>
… immutability<br/>
Benjamin Young: Immutable header <a href="https://tools.ietf.org/html/rfc8246">https://tools.ietf.org/html/rfc8246</a><br/>
Rob Sanderson: I believe there is no argument about this being a good functionality—the question is just, how do we do this in practice?<br/>
… is this an HTTP thing?<br/>
Ivan Herman: We are overloading the term “frozen”.<br/>
Dan Brickley: Similar metaphors, but not the same.<br/>
Benjamin Young: There is an identifier-based approach, and for schema.org the semantics have changed<br/>
… over time<br/>
Dan Brickley: well, it’s always meant schema.org, but we have resolved it in different ways, because of the history<br/>
… we have just kept adding terms, and the context just keeps growing<br/>
Gregg Kellogg: You might be able to pare it down with @vocab<br/>
Dan Brickley: It’s rarely been the case that we don’t have to touch it for a long period of time<br/>
… and there’s constantly things to fix<br/>
Benjamin Young: That’s the POV that this identifier will always get you the most up-to-date, “best” version of the resource<br/>
… but for the way I work, which uses separate context documents for different versions, would behave completely differently<br/>
… so one proposal is to bake version into the identifier, and another is to seal the context<br/>
Dan Brickley: Not too worried about that part of the problem: It’s not inconceivable that we might maintain a couple of high-value vocabs, but much of schema.org isn’t used now<br/>
… and for the sealed context question, another approach– perhaps allow to specify import order and thereby prevent inappropriate overrides<br/>
Gregg Kellogg: looking at the mechanism by which a processor can be encouraged to not constantly be fetching context,<br/>
… . HTTP has cache-control, and we suggest using it, but that doesn’t seems to be enough.<br/>
… so can we add some of the HTTP semantics right inside the context?<br/>
… e.g. “this is valid for this time, do not refetch within that time”<br/>
… processing tools could even throw on an inappropriate retrieval<br/>
… we’d also like to be able to “preload” contexts (prefill a cache).<br/>
Dan Brickley: We are reliving the XML Catalog discussions from couple decades back, <a href="https://en.wikipedia.org/wiki/XML_catalog">https://en.wikipedia.org/wiki/XML_catalog</a><br/>
Ivan Herman: I am afraid of conneg and HTTP headers, which are great, BUT many users cannot control them<br/>
… relying on that is attractive to a spec, but may not be a good solution<br/>
… so gkellogg’s suggest is uglier than relying on HTTP headers, but way more secure<br/>
… the schema.org example shows us that many context cannot be sealed.<br/>
… the “freezing” (no bad overrides) things—I’m guilty of that myself<br/>
… we do that on top of schema.org in publishing<br/>
Dan Brickley: We’re fine with that!<br/>
Ivan Herman: sealing a popular context could create problems for that<br/>
Dan Brickley: Sure, we can do conneg. But it’s frustrating as a vocab provider. For the rest of the site we are moving to pure static hosting.<br/>
… we would like our work as vocab providers to end with creating files<br/>
Leonard Rosenthol: Other vocabulary providers have a different approach. In our defns and vocabs, we have a policy that says<br/>
… once this is stable, any future version must be backwards-compatible<br/>
… can’t remove fields, can’t change value types, etc.<br/>
… in part because we didn’t want to deal with versioning<br/>
… but we also maintain a registry, so at any time anyone can go and get a schema<br/>
… so we get some of the benefits (e.g. we don’t have to do unneeded fetches)<br/>
… we don’t have to worry about the versioning because of the policy<br/>
Dan Brickley: two things where I’ve been raising concerns around @context<br/>
… when you’re a search engine, you may not have all the resources in hand at once<br/>
… also, @context doesn’t work for IoT, where devices are resource-constrained<br/>
… they don’t want to be fetching stuff across the network<br/>
… not sure whether “frozen” or “sealed” is the right metaphor<br/>
… but the assumption that fetching a @context is trivial isn’t necessarirly a good one<br/>
… 1.1 should not force many fetches, e.g. because of privacy concerns<br/>
Ivan Herman: understood, but how do we avoid the problem?<br/>
Dan Brickley: We shouldn’t allow the difficulty of the problem to prevent us from facing it.<br/>
Rob Sanderson: We’ll be talking to the IoT folks this afternoon.<br/>
Leonard Rosenthol: Why (other than parsing) do you need to fetch contexts?<br/>
<b>others:</b> Can’t interpret the data at all w/o the context<br/>
Leonard Rosenthol: Doesn’t mean that you have to fetch it, does it?<br/>
Dan Brickley: We ran into this with RDF/XML—we forced you to put all the semantics into the instance. Made the syntax much disliked.<br/>
Benjamin Young: <a href="https://json-ld.org/spec/latest/json-ld-api-best-practices/#cache-context">https://json-ld.org/spec/latest/json-ld-api-best-practices/#cache-context</a><br/>
Dan Brickley: JSON-LD went the other way, It isn’t even the semantics (in terms of the rdfs/owl model), it is very basic graph structure issues. Does “foo”:”bar” expand to “bar” or <a href="http://..../bar">http://..../bar</a> URI<br/>
Benjamin Young: There is to be a best-practice document, which can discuss these issues.<br/>
… the docs may say you can fetch all the time, but the tools understand how bad an idea that is.<br/>
Benjamin Young: I manually solve this problem, and it’s sort of like what we would want<br/>
… but we haven’t encouraged people to create workflows that are safe in that way<br/>
… users don’t necessarily even know that they should know HTTP at the depth needed for control caching<br/>
Luc Audrain: in Publishing, we are using JSON-LD to build metadata about books, and push it to webpages. We have, today, standards like ONIX, which are in use all over the world. But we know we have qualifications on our metadata. E.g. we might send a link to a cover image. When the book goes on sale, we might change the image to include the new price. We assume people refetch to get the updated image. It’s a similar problem. It would be nice if we could provide this.<br/>
Rob Sanderson: That’s at a different level, the level of instances. They will always require refetching. That’s not quite within our work.<br/>
<b>paul:</b> Can someone define the term “sealed”?<br/>
… who makes that decision?<br/>
Rob Sanderson: the publisher would decide that.<br/>
… that’s the feature that prevents overrides.<br/>
… for the other feature (content-addressable contexts)…<br/>
… to the extent that we want to include HTTP-type features to control/prevent fetching<br/>
… What is the extent to which we should go, to make that easy for devs?<br/>
Dan Brickley: In RDFS, W3C Working Draft 14 August 1998 <a href="https://www.w3.org/TR/1998/WD-rdf-schema-19980814/">https://www.w3.org/TR/1998/WD-rdf-schema-19980814/</a> we wrote “”"”Since an RDF Schema URI unambiguously identifies a single version of a schema, RDF processors (and Web caches) should be able to safely store copies of RDF schema graphs for an indefinite period. The problems of RDF schema evolution share many characteristics with XML DTD version management and the general problem of Web resource versioning.”<br/>
Dan Brickley: “Is is expected that a general approach to these issues will presented in a future version of this document, in co-ordination with other W3C activities. Future versions of this document may also offer RDF specific guidelines: for example, describing how a schema could document its relationship to preceding versions.””””<br/>
Ivan Herman: there is an analogy that might inspire us<br/>
… it’s like the way that CSS handles fonts<br/>
… they have an indirection. I define a font symbol, to which I can attach URIs or filenames<br/>
… the processor picks the first that is available.<br/>
… . so e.g. I could perhaps make a list, with my file of schema.org first, then the network address.<br/>
… . that’s what CSS does—they have the same problem (in their case huge font files)<br/>
… how could we shoehorn this into the syntax?<br/>
Leonard Rosenthol: You’d have to change the meaning of @context<br/>
Gregg Kellogg: The fact that there is a practice in CSS is good.<br/>
… piggybacking on an existing pattern in CSS will make arch review easier<br/>
Dan Brickley: it may be worth talking to the CSS folks to see how that feature is working out in practice<br/>
Rob Sanderson: Seems like something we could put into the API spec.<br/>
… if cache management was part of the API<br/>
… as opposed to reimplementing another document loader<br/>
Ivan Herman: -> <a href="https://www.w3.org/TR/css-fonts-3/#font-face-rule">https://www.w3.org/TR/css-fonts-3/#font-face-rule</a> Font face rule in CSS<br/>
Leonard Rosenthol: The problem w/ putting it into the API is that you’ve got to think of the various devices on which it might run– what about embedding devices, e.g.?<br/>
… the API must be flexible enough to let clients control the amount of caching that takes place.<br/>
Simon Steyskal: <a href="https://drafts.csswg.org/css-font-loading-3/">https://drafts.csswg.org/css-font-loading-3/</a> ?<br/>
Gregg Kellogg: The API spec does permit that—we only spec the relevant behavior<br/>
Ivan Herman: There are some nice examples from the CSS doc linked above<br/>
Dan Brickley: Is anyone here tracking the WebPacakging work?<br/>
… seems to address the problem of leaking URLs<br/>
… i.e. queries from Google<br/>
… it’s also about what happens when you don’t retrieve from the resource’s identifier, but from somewhere else, which is the same problem<br/>
… different timescales to cultural heritage, bu the same underlying problem!<br/>
Ivan Herman: Yes, but IIUC not something to change in the spec<br/>
Benjamin Young: the thing that is “hiding” in the WebPackage is that you don’t get the content from the content owner.<br/>
… there is no way to discover the webpackage from the live URL<br/>
Dan Brickley: There are many ways to get content. How you get content is a different question from JSON-LD– we don’t have to solve it.<br/>
… we might look at this in terms of parser APIs. How do parsers report the timeliness of their operations?<br/>
… we might want to say that JSON-LD doesn’t mandate the only parser APIs—to create some space in which to expand/eplore<br/>
… I want the schema.org contexts to be available into the future…<br/>
Harold Solbrig: The ShEx spec states that to be valid JSON ShEx, the context must have a specific URI<br/>
… that muddles the identity of the operation with the identity of a resource involved therewith<br/>
… what do we do with contexts that may never resolves?<br/>
Gregg Kellogg: For ShEx on the web, we established a media type. Then we gave rules for that media type.<br/>
Rob Sanderson: Seems like there’s a general feeling that there are many possible solutions to this issue, and baking something into the specs might be shortsighted.<br/>
Dan Brickley: the more I think about it, the more I like the idea of the poor parser just reporting what it did, weaknesses and all<br/>
Ivan Herman: We could almost verbatim copy what CSS did<br/>
** Gregg gkellogg** and Leonard Rosenthol: but that would break extant parsers<br/>
Ivan Herman: No, we could add more syntax for this purpose, not change @context<br/>
Dan Brickley: Who uses this<br/>
Ivan Herman: Whoever publishes data.<br/>
Dan Brickley: That’s tens of millions of sites, thousands of which will be hacked….<br/>
Benjamin Young: it’s different from fonts—you have fallbacks in that case, and @context is more central to JSON-LD than fonts are to CSS<br/>
— BREAK —<br/>
Benjamin Young: it would be good to have a decision around the approach<br/>
… cache loading into the instance (eg. font-face), http-level info (in the context doc)<br/>
Gregg Kellogg: there is some precedent on http changes<br/>
Rob Sanderson: or we can change things at the API level (since we have doc loading there)<br/>
… so that library writers bear the cost<br/>
Gregg Kellogg: one thing we could do is change the doc loader about how it looks for the context - eg. prescribe the specifics - as well as specific support for “side lookups”<br/>
… that would lead to greater consistency<br/>
… doc loading is in the specs<br/>
Benjamin Young: API spec area about Document Loading <a href="https://w3c.github.io/json-ld-api/#remote-document-and-context-retrieval">https://w3c.github.io/json-ld-api/#remote-document-and-context-retrieval</a><br/>
Rob Sanderson: can we promote (make more obvious) the doc loader in the API doc?<br/>
… perhaps make it a top level item?<br/>
Gregg Kellogg: this comes back to best practice. Algos described in API.<br/>
… our practice has been to put a thin veneer over the APIs but didn’t do that for doc loader. But we could<br/>
… there is a non-normative features section that we could also use. (eg. “do it this way”)<br/>
… we could describe that sources of contexts may require excessing loading (etc.)<br/>
… what does WOT do?<br/>
Rob Sanderson: don’t forget privacy/security<br/>
Gregg Kellogg: there are things we expect them to do (from a syntax perspective), and they won’t read the API doc<br/>
Benjamin Young: the section “remote doc…” could easily be renamed. (and I like everything y’all were saying)<br/>
… also want to make sure we highlight the security./privacy stuff (not just about “remote”)<br/>
… also a bunch of work in best practices to explain this. (and nothing in syntax)<br/>
Adam Soroka: do we want to talk about other situations where we retrieve docs? or is it just context?<br/>
Gregg Kellogg: there is also a section on expansion which talks about remote IRIs and documents.<br/>
Adam Soroka: so maybe we should not just put this in terms of context<br/>
Gregg Kellogg: but you might not want the entire JSON-LD doc reloaded each time either, so cache-control would be useful there too. (does this belong in the body)<br/>
Benjamin Young: my data shouldn’t be that smart (about caching)<br/>
Rob Sanderson: the data carries ontology and not necessary processing<br/>
… to ivan’s point about fallbacks. Today there is a callback (which shouldn’t need to change) and the list of things to retrieve (which we would)<br/>
… unless there is a way for the doc loader to get a list of URLs to work from (in order of precedence)<br/>
Ivan Herman: I produce my data an want to publish it, and I have a local context file and will point to it first and then a remote version.<br/>
Gregg Kellogg: context-path/reference, it could interact with the doc loader<br/>
Ivan Herman: but we need a syntax too<br/>
Adam Soroka: do the things got to an existing doc loader or do they find a doc loader?<br/>
… the doc loader is smarter<br/>
Gregg Kellogg: an array of strings is fairly simple to understand<br/>
Adam Soroka: but what if there are other policies that control the order the array is processed<br/>
Gregg Kellogg: we still have a year+ to figure otu details<br/>
Benjamin Young: we need a proposal to work from<br/>
Leonard Rosenthol: azaroth : question for ivan<br/>
Benjamin Young: in what situations would the data provider want to provide the “context set:” rather than the processor?<br/>
Ivan Herman: if I set up a WoT in my home, I have to manage them. I might include a local copy of schema.org there to avoid them all having to reach outside the network.<br/>
Gregg Kellogg: but that’s an http proxy<br/>
Ivan Herman: but it might also fall into caching model<br/>
Gregg Kellogg: webpackaging and activity streams could also help to improve caching<br/>
Adam Soroka: even a refrigerator might have a filesystem where I know what the URLs on it are, so I can point to those as local cached copies<br/>
Rob Sanderson: 15m done.<br/>
… there is agreement that we want to promote the doc loader in the API spec into something more visible and point to it from other docs (esp. about privacy/security)<br/>
… we have discussed the idea of “context list” (ordered lists of contexts) where the loader can try to find things from these multiple items<br/>
… but we need requirements and use case to help understand what to specify and where to put it<br/>
Adam Soroka: also be sure to include the horizontal bits too<br/>
Rob Sanderson: do we need a resolution?<br/>
Ivan Herman: just leave it open<br/>
Benjamin Young: can we take an action?<br/>
Gregg Kellogg: lets use some issue(s) to track ideas<br/>
Action #2: Rob Sanderson to create issues for ContextList and DocumentLoader editorial changes<br/>
</details>

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-10-26-json-ld#section7-2).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
Rob Sanderson: equally or more cross-working-group to the last one<br/>
… VC et al have security concerns around contexts that must be led by a server before the server can understand the JSON-LD<br/>
Benjamin Young: you don’t have to fetch this every time you need it, you will cache contexts, etc.<br/>
… which comes around to how contexts (as web resources) change with time<br/>
… naming on the Web—easy?<br/>
… each of the communities using the tech can resolve these things. we need the TAG to advice on the nuances of things<br/>
… like content hashes, etc.<br/>
Rob Sanderson: you can solve it at 3 diff layers: HTTP, where you can last-modified, etags, etc.<br/>
… in the doc itself, which can declare versioning<br/>
… or in the URI, e.g. http/example.com/v2<br/>
Dan Brickley: but do you need a context at all?<br/>
Gregg Kellogg: you can put it into the instance doc itself, but it still exists.<br/>
Benjamin Young: {"@context": {"@vocab": "<a href="http://example.com/"},">http://example.com/"},</a> "name": "made up vocab"}<br/>
Gregg Kellogg: The notion is that JSON-LD provides the context within which to interpret your JSON<br/>
… strings sometimes are dates sometimes IRIs, sometimes something else<br/>
… you need to both distinguish between these things but also allow for idiomatic JSON<br/>
Benjamin Young: which creates _:doc-id &lt;<a href="http://example.com/name>">http://example.com/name></a> "made up vocab" (in triples—where “doc-id” is completely random)<br/>
Gregg Kellogg: the context explains some of the things that API docs might explain<br/>
Dan Brickley: I had thought that the context could be derived in some other way<br/>
Benjamin Young: you can.<br/>
Adam Soroka: (from an HTTP header)<br/>
Dan Brickley: is this wrong then?<br/>
Dan Brickley: { "@vocab": "<a href="https://schema.org/",">https://schema.org/",</a> "@type": "Volcano", "sameAs": "<a href="https://www.wikidata.org/wiki/Q2586153",">https://www.wikidata.org/wiki/Q2586153",</a> "name": "Zuidwal volcano", "description": "The Zuidwal volcano is an extinct volcano in the Netherlands at more than 2 km (6,600 ft) below ground ..."}<br/>
Benjamin Young: latest syntax spec <a href="https://w3c.github.io/json-ld-syntax/">https://w3c.github.io/json-ld-syntax/</a><br/>
Rob Sanderson: the TAG issue for guidance is — this caching question is much broader that JSON-LD.<br/>
… many systems do this kind of “apply one resource to another to clarify”<br/>
… e.g a CSS stylesheet—if it changes over time the rendered HTML will look very different<br/>
… in a knowledge graph context, that kind of change is much more dangerous<br/>
… guidance for mitigating those concerns in the spec rather than leaving it up to broader discussion about change over time on the web<br/>
Benjamin Young: Link header looks like: Link: <context.jsonld>; rel="<a href="http://www.w3.org/ns/json-ld#context";">http://www.w3.org/ns/json-ld#context";</a> type="application/ld+json"<br/>
Hadley Beeman: so remote change can affect local things—how is this different from old concerns about linking?<br/>
Dan Brickley: the WoT folks chose a syntax that requires this additional context resource—that’s what causes this to be different<br/>
… as long as you need the context doc to interpret and act on the data, you have opened this security hole<br/>
Hadley Beeman: so what about caching?<br/>
Adam Soroka: WoT operates on much longer timescales — years in many cases.<br/>
Dan Brickley: one thing we care about is being a planet-scale search engine, the other is about lightbulbs in your home<br/>
Benjamin Young: you can’t change what happens in the lightbulb without changing the context used for data there<br/>
… you can update when you update the code<br/>
… the URI of the context really is a URI (an identifier), not a location, but it ends up being used as one<br/>
Hadley Beeman: I still hear this either being “we have to solve the problems of building the IoT” or “the network knows something about me because of what I looked at”<br/>
… which are both larger problems<br/>
Dan Brickley: no, it’s different — because now the lightbulb is not a user agent, but it is broadcasting info about you<br/>
Benjamin Young: our API spec says you can implement document loading any way you want, yay!<br/>
… but that doesn’t really solve the problem<br/>
… we have this elsewhere, e.g. clickjacking<br/>
… the answer is Single Domain policies, which is utterly inflexible and unwebby<br/>
… we want to have ids that can be safely resolved<br/>
… we would like a webby trust model<br/>
Hadley Beeman: if we do that, we say this is no longer a user agent (the light bulb)<br/>
… you are making an explicit decision that has privacy remifications—you need to be aware of that<br/>
Dan Brickley: (mitigation sketches being: parser reports, and web packaging for out-of-band context bundles with integrity checks, e.g. via homehubs etc)<br/>
Dan Brickley: I am unaware of any context that is useful and has gone unchanged for more than a few weeks<br/>
… we’re stuck between refreshing and getting the best new stuff<br/>
… and broadcasting your interests on the web<br/>
… but if not, you get out of date<br/>
… one thing would be for parsers to report what they’re done<br/>
Rob Sanderson: (and we carry on)<br/>
Rob Sanderson: (everyone disagrees about the weeks lifecycle, e.g. activitystreams, annotations, ldp, etc)<br/>
Dan Brickley: there are a lot of use cases for web packaging, this might connect with that<br/>
… your home env might have gotten this through some kind of bundled thing at lower frequencies.<br/>
Benjamin Young: you could have an API for updating the lightbulb<br/>
… but that can’t work from a pull side, because you can’t guarantee that the identifier will resolve the same way on the open web over time<br/>
… bringing us to blockchains, hashing, etc.<br/>
… there are lots of potential solutions on the list<br/>
… web packaging is one potential solution<br/>
Rob Sanderson: do you understand the issue well enough for us to send a ticket to TAG?<br/>
Hadley Beeman: what’s the header for this?<br/>
Benjamin Young: maybe “integrity”<br/>
Hadley Beeman: please write this up with use cases<br/>
… because otherwise we’re staying hypothetical<br/>
Benjamin Young: there is no requirement to do remote context dereferencing<br/>
… but people will<br/>
Dan Brickley: there are the specs, then there are ways you relay operate<br/>
… with JSON-LD, if you do it wrong, people flame you on the mailing list<br/>
… social pressure has forced us to become a component in a larger system—not cool!<br/>
Dan Brickley: we’d like people to get what they are expecting when they get contexts<br/>
Benjamin Young: many communities have this same problem<br/>
… with many different solutions<br/>
… that’s what makes it a TAG deal<br/>
… another big JSON-LD deployment is Mastodon (uses Activity Streams)<br/>
Adam Soroka: .. they haven’t updated their context for a long time<br/>
Benjamin Young: but it still works<br/>
… which is what makes this a Publishing WG problem—publishing that is broken because a system went down somewhere isn’t publishing as publishers understand it<br/>
</details>

**Comment by joeltg** [comment]
FWIW, I wrote a [demo document loader](https://github.com/underlay/jsonld-dweb-loader) for `dweb:/` URIs (IPFS and IPLD for now, as sketched out [here](https://github.com/ipfs/specs/pull/152#issuecomment-284628862)) and it works great (for both contexts and documents).

I'd argue that things like immutable resource integrity are problems with HTTP, not with JSON-LD's syntax. If it's important for your application, you should be using a different URI scheme that fits your needs.

**Comment by BigBlueHat** [comment]
I'd like to surface @msporny's "hashlink" email in relation to this discussion:
https://lists.w3.org/Archives/Public/public-json-ld-wg/2019Jan/0000.html

Our current approach to document loader configuration makes implementing that a possibility.

However, the approach taken in the hashlink proposal may also address some of our other concerns such as #86 and #108 which sit along side this topic.

Worth some time, regardless. 😃

**Comment by msporny** [comment]
> However, the approach taken in the hashlink proposal may also address some of our other concerns 

Yes, I'm asserting strongly that the Hashlink proposal addresses #9, #86, and #108. :)

**Comment by gkellogg** [comment]
I believe we can close this issue with no changes necessary. Perhaps a discussion in the Best Practices doc.

**Comment by azaroth42** [comment]
Resolved to close on 2019-07-12 call - https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-07-12-json-ld

**Comment by vmx** [comment]
@azaroth42 I'd like to read the meeting minutes, but the link above is a 404 for me. I also can't find them in https://github.com/w3c/json-ld-wg/tree/master/_minutes.

**Comment by BigBlueHat** [comment]
@vmx I'll be generating last Friday's minutes today. Our normal minute generating super hero is out of the office, atm, so I get to feed the bots while they're a way. :grin: I'll update this issue once they're generated. Raw logs are available (if you're in a hurry): https://www.w3.org/2019/07/12-json-ld-irc

**Comment by BigBlueHat** [comment]
@vmx here are the logs as promised! https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-07-12-json-ld

If you have specific questions or ideas about this issue at this point, it's probably best to file a new issue or send a mailing list post to our [public mailing list](https://lists.w3.org/Archives/Public/public-json-ld-wg/).

Cheers!
🎩
