### ISSUE TITLE
JSON-LD script elements (data blocks) MUST only contain valid JSON

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/json-ld-syntax#96]
The current editor's draft suggests wrapping JSON-LD in a data block with `<!--` and `-->` to avoid some HTML parsing situations. Ultimately, that means that we're suggesting that the contents of an embedded JSON-LD data block is legally *invalid* JSON-LD...which seems bad...

Consequently, I'd like to propose that we *only* specify the entity encoding of certain strings within the JSON-LD contents to avoid the potential HTML parsing mishaps described in HTML's [Restrictions on contents of script elements](https://www.w3.org/TR/html52/semantics-scripting.html#restrictions-for-contents-of-script-elements) section.

Doing that avoids encouraging invalid JSON-LD and removes the additional unique parsing steps for cleaning out the wrapping `<!--` and `-->`.

PR forthcoming.

**Comment by gkellogg** [comment]
I can support this, but we need to have some rule for dealing with comment inside of strings that could cause DOM problems, specifically `<!--`, `-->`, `<script` and `</script`. Using either or both of the current escape sequences and character references will keep the content legal JSON, but it will not be interpreted properly unless unescaping or resolving character references is performed.

Surrounding script contents with XML comments is a common practice, but may be obsolete now with HTML5, along with CDATA.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-11-30-json-ld#section7-2).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
JSON-LD script elements (data blocks) MUST only contain valid JSON<br/>
Benjamin Young: <a href="https://github.com/w3c/json-ld-syntax/issues/96">https://github.com/w3c/json-ld-syntax/issues/96</a><br/>
Benjamin Young: issue related to <a href="https://github.com/w3c/json-ld-syntax/pull/97">https://github.com/w3c/json-ld-syntax/pull/97</a><br/>
Gregg Kellogg: what I pushed up there addresses the different aspects of the HTML script content.<br/>
… HTML provides 2 mechanisms: specific backslash escapes in HTML comments, or HTML entities<br/>
… Benjamin proposed to remove the comments, to keep it valid JSON, consistently with the declared content-type.<br/>
Benjamin Young: it’s similar to injecting HTML tags in a &lt;textarea>, without breaking the textarea.<br/>
Rob Sanderson: to be sure i understand, the issue is if you have: <script>{"label": "<!--"}</script> ?<br/>
… No, thankfully, but I see the point<br/>
… And then the pain of double and quadruple escaping … Thanks for the explanation. Result = :(<br/>
Gregg Kellogg: I want to be able to copy-paste the content of the script tag into, e.g., the JSON-LD playground.<br/>
Ivan Herman: the schema.org pages is full of examples, but none of them has “pathological” examples re. content tags<br/>
… we could try to test their tools and see if they break.<br/>
… We could decide this is an author’s problem. JSON-LD in HTML is optional.<br/>
… If authors want to do that, they should know they are not on neutral ground,<br/>
Rob Sanderson: Related to what ivan said, and I agree with his opinion … Can we ask DanBri to find out what about this in current schema.org usage? There’s doubtless instances of this sort of thing (<!-- etc) in the wild, that they might be able to find (or not) with relative ease?<br/>
… and take precautions.<br/>
… Someone must have tried to put <script> in a json-ld block in some attempt to mess with Google :)<br/>
Gregg Kellogg: my tool will handle the comments; I don’t think they will render the entity escaping correctly<br/>
… We has to check with the structured data tools, and talk with danbri about it.<br/>
Benjamin Young: we need to be sure that the authors understand what happens<br/>
… and why JSON-LD from an HTML script tag does not behave differently from JSON-LD from a file<br/>
Pierre-Antoine Champin: I’m not sure about a detail: what if I put an entity in a script tag?<br/>
… from JS code, do I get the entity? or is it unescaped?<br/>
Ivan Herman: "name" : ["my name is <in this>", "&amp;lt;lll&gt;"] works in the structural testing tool<br/>
Ivan Herman: both these thinks work as expected<br/>
… both the “<” and the “<” appear as “<”<br/>
Benjamin Young: that’s what you see, but the raw result may be different<br/>
Gregg Kellogg: A better test might be ”name”: [“</script>”]<br/>
Ivan Herman: exploring how <a href="https://search.google.com/structured-data/testing-tool">https://search.google.com/structured-data/testing-tool</a> handles things<br/>
Gregg Kellogg: I think you’re right that they’re unescaping them<br/>
… but these are such rare cases<br/>
Rob Sanderson: +1 to “It hurts when I do this” … “Don’t do that then”<br/>
Gregg Kellogg: maybe we get rid of this whole notation, by saying you MUST only embed text which can be extracted via the HTML DOM<br/>
Benjamin Young: doesn’t that place the constraint on all of JSON-LD that it could never contain </script><br/>
Gregg Kellogg: yes. that<br/>
David I. Lehn: i’d like to note you are furthering the difficulty in writing obfuscated json-ld.<br/>
Rob Sanderson: Potentially also removing an attack vector, security wise<br/>
… But not HTML in JSON(-LD or not) in HTML<br/>
… +1 to it being addressed<br/>
Rob Sanderson: Bye!<br/>
</details>

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-12-07-json-ld#section4-1).

- `RESOLVED:  close #97 as fixed with recent merges; other issues raised in #100`
<details><summary><i class="differentiate">View the transcript</i></summary>
4.1. Remove the need for wrapping comment-open/comment-close text in data blocks<br/>
Benjamin Young: <a href="https://github.com/w3c/json-ld-syntax/pull/97">https://github.com/w3c/json-ld-syntax/pull/97</a><br/>
Gregg Kellogg: most of these are related to PRs just discussed, but not all<br/>
Gregg Kellogg: <a href="https://github.com/w3c/json-ld-syntax/issues/96">https://github.com/w3c/json-ld-syntax/issues/96</a><br/>
Benjamin Young: current draft talks now about html entities for escaping<br/>
Gregg Kellogg: given that it has to be valid json-ld, how do we deal with escaped entities<br/>
… leaves us with problem of how to represent &lt;script> tags and comments in json?<br/>
… so we could close 97 and leave 100 for further discussion<br/>
Benjamin Young: one option is to mark propose closing and discuss more later<br/>
Gregg Kellogg: DanBri involved and noted in discussion (of this or another related issue 100)<br/>
Proposed resolution: close #97 as fixed with recent merges; other issues raised in #100 (Benjamin Young)<br/>
Gregg Kellogg: +1<br/>
David Newbury: +1<br/>
Tim Cole: +1<br/>
Benjamin Young: +1<br/>
Ivan Herman: +1<br/>
Resolution #2: close #97 as fixed with recent merges; other issues raised in #100<br/>
</details>

**Comment by BigBlueHat** [comment]
Think I missed referencing this issue in the resolution we used last week. I believe the current text in https://w3c.github.io/json-ld-syntax/#restrictions-for-contents-of-json-ld-script-elements settles this nicely, fwiw, so closing as I believe it's both fixed and we had consensus to match. 😄
